def ayuda():
    print('Comandos disponibles en PartDesignWorkbench:')
    print('  base        - Subconjunto: Body, NewSketch, Clone, SubShapeBinder')
    print('  additive    - Subconjunto: features y primitivas aditivas (Pad, Revolution, Box, Cone, etc.)')
    print('  subtractive - Subconjunto: features y primitivas sustractivas (Pocket, Groove, Hole, etc.)')
    print('  modify      - Subconjunto: modificadores de forma (Fillet, Chamfer, Draft, Thickness, Boolean)')
    print('  transform   - Subconjunto: patrones y transformaciones (LinearPattern, Mirrored, PolarPattern, etc.)')
    print('  manage      - Subconjunto: gestión del árbol y preferencias (MoveFeature, MoveTip, Preferences, etc.)')
    print('\nPrecondición General:')
    print('  Casi todos los comandos requieren un Body activo. Operaciones aditivas/sustractivas y transformaciones')
    print('  también requieren la selección previa de un boceto (sketch) o de operaciones/aristas del modelo.')
