def ayuda():
    print('Comandos disponibles en este nivel:')
    print('  clone     - Hace una copia vinculada de una figura. Si el original cambia, el clon también cambia.')
    print('              Requiere: Figura (objeto o lista de objetos).')
    print('')
    print('  downgrade - Convierte una figura en algo más simple (ej. separa una cara en líneas sueltas).')
    print('              Requiere: Una figura o lista de figuras (objeto).')
    print('              Nota: Es lo contrario de Draft_Upgrade, devuelve una figura de menor nivel.')
    print('')
    print('  sketch    - Convierte una figura de Draft en un Sketch, o un Sketch en figuras de Draft.')
    print('              Requiere: Una figura de Draft o un Sketch (objeto).')
    print('              Nota: Devuelve un Sketch si se parte de una figura Draft, o figuras Draft si se parte de un Sketch.')
    print('')
    print('  edit      - Pone una figura en modo edición para mover sus puntos y cambiar su forma arrastrándolos.')
    print('              Requiere: Una figura de Draft (línea, arco, polilínea, etc.).')
    print('')
    print('  fillet    - Crea un redondeo (acuerdo) entre dos líneas o segmentos.')
    print('              Requiere: Lista de dos objetos (Line/Wire), radius (float/número).')
    print('              Nota: Requiere que los objetos se toquen o crucen en un punto.')