"""Descripciones del manual: PartDesign y Sketcher (ver desc_explorer.py para el formato)."""

G = {
    "workbench/partdesign": "body",
    "workbench/partdesign/base": "doc",
    "workbench/partdesign/additive": "body",
    "workbench/partdesign/subtractive": "bodysolid",
    "workbench/partdesign/modify": "bodysolid",
    "workbench/partdesign/transform": "bodysolid",
    "workbench/partdesign/manage": "body",
    "workbench/sketcher": "sketch",
}

D = {
    # -------------------------------------------------------------- PartDesign
    "workbench/partdesign": ("Diseño paramétrico de piezas sólidas sobre un cuerpo (Body).",
                             "Parametric design of solid parts on a Body.",
                             "Projeto paramétrico de peças sólidas sobre um corpo (Body)."),
    "workbench/partdesign/base": ("Cuerpo, croquis nuevo, clones y enlace de subformas.",
                                  "Body, new sketch, clones and sub-shape binders.",
                                  "Corpo, croqui novo, clones e vínculo de subformas."),
    "workbench/partdesign/base/body": ("Crea el cuerpo (Body) que agrupa las operaciones.", "Creates the Body that groups the features.", "Cria o corpo (Body) que agrupa as operações.", "doc"),
    "workbench/partdesign/base/newsketch": ("Crea un croquis nuevo sobre un plano base o una cara plana del sólido, elegidos por voz.", "Creates a new sketch on a base plane or a flat face of the solid, chosen by voice.", "Cria um croqui novo sobre um plano base ou uma face plana do sólido, escolhidos por voz.", "doc"),
    "workbench/partdesign/base/clone": ("Crea una copia dependiente de un cuerpo u operación.", "Creates a dependent copy of a body or feature.", "Cria uma cópia dependente de um corpo ou operação.", "sel"),
    "workbench/partdesign/base/subshapebinder": ("Referencia geometría de otro cuerpo dentro del cuerpo activo.", "References geometry of another body inside the active body.", "Referencia a geometria de outro corpo dentro do corpo ativo.", "body"),

    "workbench/partdesign/additive": ("Agrega material: extrusiones, revoluciones, barridos y primitivas.",
                                      "Adds material: extrusions, revolutions, sweeps and primitives.",
                                      "Adiciona material: extrusões, revoluções, varreduras e primitivas."),
    "workbench/partdesign/additive/pad": ("Extruye el croquis seleccionado para crear un sólido (Pad).", "Extrudes the selected sketch to create a solid (Pad).", "Extrude o croqui selecionado para criar um sólido (Pad).", "bodysk"),
    "workbench/partdesign/additive/revolution": ("Revoluciona el croquis alrededor del eje vertical del croquis; permite elegirlo por voz.", "Revolves the sketch about its vertical axis; lets you pick it by voice.", "Revoluciona o croqui em torno do eixo vertical do croqui; permite escolhê-lo por voz.", "bodysk"),
    "workbench/partdesign/additive/additivehelix": ("Barre un perfil a lo largo de una hélice (roscas, resortes).", "Sweeps a profile along a helix (threads, springs).", "Varre um perfil ao longo de uma hélice (roscas, molas).", "bodysk"),
    "workbench/partdesign/additive/additiveloft": ("Crea un sólido con transición suave entre varios perfiles.", "Creates a solid with a smooth transition between several profiles.", "Cria um sólido com transição suave entre vários perfis.", "bodysk2"),
    "workbench/partdesign/additive/additivepipe": ("Barre un perfil a lo largo de una trayectoria.", "Sweeps a profile along a path.", "Varre um perfil ao longo de uma trajetória.", "bodysk2"),
    "workbench/partdesign/additive/additivebox": ("Inserta una caja primitiva aditiva.", "Inserts an additive primitive box.", "Insere uma caixa primitiva aditiva."),
    "workbench/partdesign/additive/additivecone": ("Inserta un cono o tronco de cono aditivo.", "Inserts an additive cone or truncated cone.", "Insere um cone ou tronco de cone aditivo."),
    "workbench/partdesign/additive/additivecylinder": ("Inserta un cilindro aditivo.", "Inserts an additive cylinder.", "Insere um cilindro aditivo."),
    "workbench/partdesign/additive/additiveellipsoid": ("Inserta un elipsoide aditivo.", "Inserts an additive ellipsoid.", "Insere um elipsoide aditivo."),
    "workbench/partdesign/additive/additiveprism": ("Inserta un prisma regular aditivo.", "Inserts an additive regular prism.", "Insere um prisma regular aditivo."),
    "workbench/partdesign/additive/additivesphere": ("Inserta una esfera aditiva.", "Inserts an additive sphere.", "Insere uma esfera aditiva."),
    "workbench/partdesign/additive/additivetorus": ("Inserta un toroide aditivo.", "Inserts an additive torus.", "Insere um toroide aditivo."),
    "workbench/partdesign/additive/additivewedge": ("Inserta una cuña aditiva.", "Inserts an additive wedge.", "Insere uma cunha aditiva."),
    "workbench/partdesign/additive/pad_sketch": ("Extruye el croquis y pide la altura por voz.", "Extrudes the sketch and asks for the height by voice.", "Extrude o croqui e pede a altura por voz.", "bodysk"),
    "workbench/partdesign/additive/pad_by_length": ("Extruye por una medida dictada.", "Extrudes by a dictated length.", "Extrude por uma medida ditada.", "bodysk"),
    "workbench/partdesign/additive/revolve_by_angle": ("Revoluciona un croquis elegido por voz por el ángulo dictado.", "Revolves a sketch chosen by voice by the dictated angle.", "Revoluciona um croqui escolhido por voz pelo ângulo ditado.", "bodysk"),
    "workbench/partdesign/additive/loft_profiles": ("Mezcla perfiles dictando las medidas.", "Blends profiles with dictated sizes.", "Mistura perfis com medidas ditadas.", "bodysk2"),

    "workbench/partdesign/subtractive": ("Quita material: cortes, agujeros, ranuras y primitivas negativas.",
                                         "Removes material: pockets, holes, grooves and negative primitives.",
                                         "Remove material: cortes, furos, ranhuras e primitivas negativas."),
    "workbench/partdesign/subtractive/pocket": ("Vacía material extruyendo el croquis hacia el interior.", "Removes material by extruding the sketch inward.", "Remove material extrudindo o croqui para o interior.", "bodysksolid"),
    "workbench/partdesign/subtractive/groove": ("Quita material girando el croquis alrededor de un eje.", "Removes material by revolving the sketch about an axis.", "Remove material girando o croqui em torno de um eixo.", "bodysksolid"),
    "workbench/partdesign/subtractive/hole": ("Crea orificios roscados o lisos a partir de un croquis.", "Creates threaded or plain holes from a sketch.", "Cria furos roscados ou lisos a partir de um croqui.", "bodysksolid"),
    "workbench/partdesign/subtractive/subtractivebox": ("Resta una caja del sólido.", "Subtracts a box from the solid.", "Subtrai uma caixa do sólido."),
    "workbench/partdesign/subtractive/subtractivecone": ("Resta un cono del sólido.", "Subtracts a cone from the solid.", "Subtrai um cone do sólido."),
    "workbench/partdesign/subtractive/subtractivecylinder": ("Resta un cilindro del sólido.", "Subtracts a cylinder from the solid.", "Subtrai um cilindro do sólido."),
    "workbench/partdesign/subtractive/subtractiveellipsoid": ("Resta un elipsoide del sólido.", "Subtracts an ellipsoid from the solid.", "Subtrai um elipsoide do sólido."),
    "workbench/partdesign/subtractive/subtractivehelix": ("Quita material barriendo un croquis en hélice.", "Removes material by sweeping a sketch along a helix.", "Remove material varrendo um croqui em hélice.", "bodysksolid"),
    "workbench/partdesign/subtractive/subtractiveloft": ("Quita material interpolando entre varios perfiles.", "Removes material by blending several profiles.", "Remove material interpolando vários perfis.", "bodysk2solid"),
    "workbench/partdesign/subtractive/subtractivepipe": ("Quita material barriendo un croquis a lo largo de una trayectoria.", "Removes material by sweeping a sketch along a path.", "Remove material varrendo um croqui ao longo de uma trajetória.", "bodysk2solid"),
    "workbench/partdesign/subtractive/subtractiveprism": ("Resta un prisma poligonal del sólido.", "Subtracts a polygonal prism from the solid.", "Subtrai um prisma poligonal do sólido."),
    "workbench/partdesign/subtractive/subtractivesphere": ("Resta una esfera del sólido.", "Subtracts a sphere from the solid.", "Subtrai uma esfera do sólido."),
    "workbench/partdesign/subtractive/subtractivetorus": ("Resta un toroide del sólido.", "Subtracts a torus from the solid.", "Subtrai um toroide do sólido."),
    "workbench/partdesign/subtractive/subtractivewedge": ("Resta una cuña del sólido.", "Subtracts a wedge from the solid.", "Subtrai uma cunha do sólido."),
    "workbench/partdesign/subtractive/pocket_by_length": ("Vacía con una profundidad dictada.", "Pockets with a dictated depth.", "Faz o corte com uma profundidade ditada.", "bodysksolid"),
    "workbench/partdesign/subtractive/hole_by_size": ("Agujero pasante: pide el diámetro.", "Through hole: asks for the diameter.", "Furo passante: pede o diâmetro.", "bodysksolid"),
    "workbench/partdesign/subtractive/blind_hole": ("Agujero ciego (no atraviesa): pide diámetro y profundidad y perfora en cada círculo del croquis.", "Blind hole (does not go through): asks for diameter and depth and drills at each circle of the sketch.", "Furo cego (não atravessa): pede diâmetro e profundidade e fura em cada círculo do croqui.", "bodysksolid"),
    "workbench/partdesign/subtractive/groove_by_angle": ("Ranura girando el croquis un ángulo dictado.", "Groove revolving the sketch by a dictated angle.", "Ranhura girando o croqui por um ângulo ditado.", "bodysksolid"),
    "workbench/partdesign/subtractive/boolean": ("Operación booleana entre sólidos (unión, intersección, diferencia).", "Boolean operation between solids (union, intersection, difference).", "Operação booleana entre sólidos (união, interseção, diferença).", "body2"),

    "workbench/partdesign/modify": ("Redondeos, chaflanes, espesor, inclinación y grabado de texto.",
                                    "Fillets, chamfers, thickness, draft and text engraving.",
                                    "Arredondamentos, chanfros, espessura, inclinação e gravação de texto."),
    "workbench/partdesign/modify/fillet": ("Redondea las aristas seleccionadas.", "Rounds the selected edges.", "Arredonda as arestas selecionadas.", "seledge"),
    "workbench/partdesign/modify/chamfer": ("Aplica un chaflán a las aristas seleccionadas.", "Applies a chamfer to the selected edges.", "Aplica um chanfro às arestas selecionadas.", "seledge"),
    "workbench/partdesign/modify/draft": ("Inclina caras para facilitar el desmoldeo.", "Tilts faces to ease mold release.", "Inclina faces para facilitar a desmoldagem.", "selface"),
    "workbench/partdesign/modify/thickness": ("Vacía el sólido dejando paredes de grosor uniforme.", "Hollows the solid leaving walls of uniform thickness.", "Esvazia o sólido deixando paredes de espessura uniforme.", "selface"),
    "workbench/partdesign/modify/fillet_by_radius": ("Redondea aristas con el radio dictado.", "Rounds edges with the dictated radius.", "Arredonda arestas com o raio ditado.", "seledge"),
    "workbench/partdesign/modify/chamfer_by_size": ("Chaflán con la medida dictada.", "Chamfer with the dictated size.", "Chanfro com a medida ditada.", "seledge"),
    "workbench/partdesign/modify/chamfer_by_size_and_angle": ("Chaflán con medida y ángulo dictados.", "Chamfer with dictated size and angle.", "Chanfro com medida e ângulo ditados.", "seledge"),
    "workbench/partdesign/modify/thickness_by_value": ("Vacía el sólido con el espesor dictado.", "Hollows the solid with the dictated thickness.", "Esvazia o sólido com a espessura ditada.", "selface"),
    "workbench/partdesign/modify/engrave": ("Graba texto en relieve o hundido: elige cara o plano, relieve o perforación, deletrea el texto y dicta alturas.", "Engraves text raised or sunk: pick face or plane, raised or cut, spell the text and dictate heights.", "Grava texto em relevo ou rebaixado: escolhe face ou plano, relevo ou perfuração, soletra o texto e dita alturas.", "bodysolid"),

    "workbench/partdesign/transform": ("Patrones lineales y polares, simetrías y escalados.",
                                       "Linear and polar patterns, mirrors and scaling.",
                                       "Padrões lineares e polares, simetrias e escalas."),
    "workbench/partdesign/transform/linearpattern": ("Repite una operación en línea recta.", "Repeats a feature along a straight line.", "Repete uma operação em linha reta.", "selfeat"),
    "workbench/partdesign/transform/mirrored": ("Crea la simetría (espejo) de operaciones seleccionadas.", "Mirrors the selected features.", "Cria a simetria (espelho) das operações selecionadas.", "selfeat"),
    "workbench/partdesign/transform/polarpattern": ("Repite una operación en círculo.", "Repeats a feature in a circle.", "Repete uma operação em círculo.", "selfeat"),
    "workbench/partdesign/transform/multitransform": ("Combina varias transformaciones sucesivas.", "Combines several successive transformations.", "Combina várias transformações sucessivas.", "selfeat"),
    "workbench/partdesign/transform/scaled": ("Crea copias escaladas progresivamente.", "Creates progressively scaled copies.", "Cria cópias escaladas progressivamente.", "selfeat"),
    "workbench/partdesign/transform/linear_pattern": ("Patrón lineal con la cantidad y medida dictadas.", "Linear pattern with the dictated count and size.", "Padrão linear com a quantidade e medida ditadas.", "selfeat"),
    "workbench/partdesign/transform/linear_pattern_by_spacing": ("Patrón lineal con separación dictada.", "Linear pattern with dictated spacing.", "Padrão linear com espaçamento ditado.", "selfeat"),
    "workbench/partdesign/transform/polar_pattern": ("Patrón circular con cantidad y ángulo dictados.", "Circular pattern with dictated count and angle.", "Padrão circular com quantidade e ângulo ditados.", "selfeat"),
    "workbench/partdesign/transform/scaled_by_factor": ("Copias escaladas con el factor dictado.", "Scaled copies with the dictated factor.", "Cópias escaladas com o fator ditado.", "selfeat"),

    "workbench/partdesign/manage": ("Mover operaciones, la punta del cuerpo y asistentes.",
                                    "Move features, the body tip and wizards.",
                                    "Mover operações, a ponta do corpo e assistentes."),
    "workbench/partdesign/manage/movefeature": ("Mueve un objeto de un cuerpo a otro.", "Moves an object from one body to another.", "Move um objeto de um corpo para outro.", "body2"),
    "workbench/partdesign/manage/movefeatureintree": ("Reordena operaciones dentro del árbol de un cuerpo.", "Reorders features within a body's tree.", "Reordena operações dentro da árvore de um corpo.", "body"),
    "workbench/partdesign/manage/movetip": ("Define una operación como la punta (Tip) del cuerpo.", "Sets a feature as the body's Tip.", "Define uma operação como a ponta (Tip) do corpo.", "body"),
    "workbench/partdesign/manage/preferences": ("Abre las preferencias de PartDesign.", "Opens the PartDesign preferences.", "Abre as preferências do PartDesign.", "none"),
    "workbench/partdesign/manage/wizardshaft": ("Asistente para crear ejes con análisis de fuerzas.", "Wizard to create shafts with force analysis.", "Assistente para criar eixos com análise de forças.", "none"),

    # --------------------------------------------------------------- Sketcher
    "workbench/sketcher": ("Croquis 2D con geometría, restricciones y herramientas de edición.",
                           "2D sketches with geometry, constraints and editing tools.",
                           "Croquis 2D com geometria, restrições e ferramentas de edição."),
    "workbench/sketcher/geometry": ("Entidades geométricas del croquis y cierre del croquis.", "Sketch geometric entities and leaving the sketch.", "Entidades geométricas do croqui e saída do croqui."),
    "workbench/sketcher/geometry/arc": ("Arcos.", "Arcs.", "Arcos."),
    "workbench/sketcher/geometry/arc/center": ("Arco por centro, radio y ángulos inicial y final.", "Arc by center, radius and start and end angles.", "Arco por centro, raio e ângulos inicial e final."),
    "workbench/sketcher/geometry/arc/3point": ("Arco por dos extremos y un punto intermedio.", "Arc by two endpoints and a middle point.", "Arco por dois extremos e um ponto intermediário."),
    "workbench/sketcher/geometry/arc/create_by_center": ("Arco por centro y ángulos dictados.", "Arc by dictated center and angles.", "Arco por centro e ângulos ditados."),
    "workbench/sketcher/geometry/arc/create_by_3points": ("Arco por tres puntos dictados.", "Arc by three dictated points.", "Arco por três pontos ditados."),
    "workbench/sketcher/geometry/arc_slot": ("Ranuras curvas.", "Curved slots.", "Ranhuras curvas."),
    "workbench/sketcher/geometry/arc_slot/arc_ends": ("Ranura curva con extremos redondeados.", "Curved slot with rounded ends.", "Ranhura curva com extremos arredondados."),
    "workbench/sketcher/geometry/arc_slot/flat_ends": ("Ranura curva con extremos planos.", "Curved slot with flat ends.", "Ranhura curva com extremos planos."),
    "workbench/sketcher/geometry/bspline": ("Curvas B-Spline.", "B-Spline curves.", "Curvas B-Spline."),
    "workbench/sketcher/geometry/bspline/create": ("B-Spline por puntos de control.", "B-Spline by control points.", "B-Spline por pontos de controle."),
    "workbench/sketcher/geometry/bspline/interpolation": ("B-Spline que pasa exactamente por los puntos.", "B-Spline passing exactly through the points.", "B-Spline que passa exatamente pelos pontos."),
    "workbench/sketcher/geometry/bspline/periodic": ("B-Spline periódica (cerrada) por puntos de control.", "Periodic (closed) B-Spline by control points.", "B-Spline periódica (fechada) por pontos de controle."),
    "workbench/sketcher/geometry/bspline/periodicinterp": ("B-Spline cerrada que interpola los puntos.", "Closed B-Spline interpolating the points.", "B-Spline fechada que interpola os pontos."),
    "workbench/sketcher/geometry/tools": ("Herramientas para editar B-Splines.", "Tools to edit B-Splines.", "Ferramentas para editar B-Splines.", "bspline"),
    "workbench/sketcher/geometry/tools/tonurbs": ("Convierte la curva en NURBS.", "Converts the curve to NURBS.", "Converte a curva em NURBS."),
    "workbench/sketcher/geometry/tools/decrease": ("Reduce en uno el grado de la B-Spline.", "Lowers the B-Spline degree by one.", "Reduz em um o grau da B-Spline."),
    "workbench/sketcher/geometry/tools/increase": ("Aumenta en uno el grado de la B-Spline.", "Raises the B-Spline degree by one.", "Aumenta em um o grau da B-Spline."),
    "workbench/sketcher/geometry/tools/knot": ("Inserta un nudo (knot) en la B-Spline.", "Inserts a knot into the B-Spline.", "Insere um nó (knot) na B-Spline."),
    "workbench/sketcher/geometry/tools/join": ("Une dos curvas B-Spline continuas.", "Joins two continuous B-Spline curves.", "Une duas curvas B-Spline contínuas."),
    "workbench/sketcher/geometry/circle": ("Círculos.", "Circles.", "Círculos."),
    "workbench/sketcher/geometry/circle/create": ("Círculo por centro y radio (ventana de voz).", "Circle by center and radius (voice window).", "Círculo por centro e raio (janela de voz)."),
    "workbench/sketcher/geometry/circle/3point": ("Círculo que pasa por tres puntos.", "Circle through three points.", "Círculo que passa por três pontos."),
    "workbench/sketcher/geometry/circle/create_by_center_radius": ("Círculo con centro y radio dictados.", "Circle with dictated center and radius.", "Círculo com centro e raio ditados."),
    "workbench/sketcher/geometry/circle/create_by_3points": ("Círculo por tres puntos dictados.", "Circle by three dictated points.", "Círculo por três pontos ditados."),
    "workbench/sketcher/geometry/ellipse": ("Elipses y cónicas.", "Ellipses and conics.", "Elipses e cônicas."),
    "workbench/sketcher/geometry/ellipse/center": ("Elipse por centro y radios mayor y menor.", "Ellipse by center and major and minor radii.", "Elipse por centro e raios maior e menor."),
    "workbench/sketcher/geometry/ellipse/3points": ("Elipse por tres puntos.", "Ellipse by three points.", "Elipse por três pontos."),
    "workbench/sketcher/geometry/ellipse/elliptic": ("Arco de elipse con ángulos dictados.", "Elliptical arc with dictated angles.", "Arco de elipse com ângulos ditados."),
    "workbench/sketcher/geometry/ellipse/hyperbolic": ("Arco de hipérbola.", "Hyperbola arc.", "Arco de hipérbole."),
    "workbench/sketcher/geometry/ellipse/parabolic": ("Arco de parábola.", "Parabola arc.", "Arco de parábola."),
    "workbench/sketcher/geometry/heptagon": ("Heptágonos.", "Heptagons.", "Heptágonos."),
    "workbench/sketcher/geometry/heptagon/create": ("Heptágono regular por centro y radio.", "Regular heptagon by center and radius.", "Heptágono regular por centro e raio."),
    "workbench/sketcher/geometry/hexagon": ("Hexágonos.", "Hexagons.", "Hexágonos."),
    "workbench/sketcher/geometry/hexagon/create": ("Hexágono regular por centro y radio.", "Regular hexagon by center and radius.", "Hexágono regular por centro e raio."),
    "workbench/sketcher/geometry/line": ("Líneas.", "Lines.", "Linhas."),
    "workbench/sketcher/geometry/line/create": ("Línea recta entre dos puntos.", "Straight line between two points.", "Linha reta entre dois pontos."),
    "workbench/sketcher/geometry/line/create_by_points": ("Línea con las cuatro coordenadas dictadas (x1, y1, x2, y2).", "Line with the four dictated coordinates (x1, y1, x2, y2).", "Linha com as quatro coordenadas ditadas (x1, y1, x2, y2)."),
    "workbench/sketcher/geometry/polygon": ("Polígonos regulares.", "Regular polygons.", "Polígonos regulares."),
    "workbench/sketcher/geometry/polygon/pentagon": ("Pentágono regular.", "Regular pentagon.", "Pentágono regular."),
    "workbench/sketcher/geometry/polygon/octagon": ("Octógono regular.", "Regular octagon.", "Octógono regular."),
    "workbench/sketcher/geometry/polygon/regular": ("Polígono regular con la cantidad de lados dictada.", "Regular polygon with the dictated number of sides.", "Polígono regular com o número de lados ditado."),
    "workbench/sketcher/geometry/polyline": ("Polilíneas.", "Polylines.", "Polilinhas."),
    "workbench/sketcher/geometry/polyline/create": ("Línea compuesta de varios segmentos.", "Line made of several segments.", "Linha composta de vários segmentos."),
    "workbench/sketcher/geometry/rectangle": ("Rectángulos.", "Rectangles.", "Retângulos."),
    "workbench/sketcher/geometry/rectangle/create": ("Rectángulo por dos esquinas opuestas.", "Rectangle by two opposite corners.", "Retângulo por dois cantos opostos."),
    "workbench/sketcher/geometry/rectangle/center": ("Rectángulo por centro y tamaño.", "Rectangle by center and size.", "Retângulo por centro e tamanho."),
    "workbench/sketcher/geometry/triangle": ("Triángulos.", "Triangles.", "Triângulos."),
    "workbench/sketcher/geometry/triangle/create": ("Triángulo por sus tres vértices.", "Triangle by its three vertices.", "Triângulo pelos seus três vértices."),
    "workbench/sketcher/geometry/new": ("Crea un croquis nuevo.", "Creates a new sketch.", "Cria um croqui novo.", "doc"),
    "workbench/sketcher/geometry/leave": ("Cierra el croquis en edición conservando el dibujo.", "Closes the sketch being edited, keeping the drawing.", "Fecha o croqui em edição mantendo o desenho."),
    "workbench/sketcher/geometry/edit": ("Edita un croquis dictando su nombre.", "Edits a sketch by dictating its name.", "Edita um croqui ditando o seu nome.", "doc"),
    "workbench/sketcher/geometry/attach": ("Adjunta un croquis a una cara o soporte dictados.", "Attaches a sketch to a dictated face or support.", "Anexa um croqui a uma face ou suporte ditados.", "doc"),
    "workbench/sketcher/geometry/grid": ("Muestra u oculta la cuadrícula del croquis.", "Shows or hides the sketch grid.", "Mostra ou oculta a grade do croqui."),
    "workbench/sketcher/arcslot": ("Ranuras de arco.", "Arc slots.", "Ranhuras de arco."),
    "workbench/sketcher/arcslot/arcends": ("Ranura curva con bordes redondeados.", "Curved slot with rounded edges.", "Ranhura curva com bordas arredondadas."),
    "workbench/sketcher/constraints": ("Restricciones dimensionales (cotas) y geométricas.", "Dimensional (size) and geometric constraints.", "Restrições dimensionais (cotas) e geométricas."),
    "workbench/sketcher/constraints/dimension": ("Cota de distancia sobre una línea.", "Distance dimension on a line.", "Cota de distância sobre uma linha."),
    "workbench/sketcher/constraints/horizontal": ("Cota horizontal entre los extremos de una línea.", "Horizontal dimension between a line's endpoints.", "Cota horizontal entre os extremos de uma linha."),
    "workbench/sketcher/constraints/vertical": ("Cota vertical entre los extremos de una línea.", "Vertical dimension between a line's endpoints.", "Cota vertical entre os extremos de uma linha."),
    "workbench/sketcher/constraints/angle": ("Cota angular entre dos líneas.", "Angular dimension between two lines.", "Cota angular entre duas linhas."),
    "workbench/sketcher/constraints/radius": ("Cota de radio de un arco o círculo.", "Radius dimension of an arc or circle.", "Cota de raio de um arco ou círculo."),
    "workbench/sketcher/constraints/diameter": ("Cota de diámetro de un círculo.", "Diameter dimension of a circle.", "Cota de diâmetro de um círculo."),
    "workbench/sketcher/constraints/distance": ("Cota de distancia entre los extremos de una línea.", "Distance dimension between a line's endpoints.", "Cota de distância entre os extremos de uma linha."),
    "workbench/sketcher/constraints/geometric": ("Relaciones geométricas entre entidades.", "Geometric relations between entities.", "Relações geométricas entre entidades."),
    "workbench/sketcher/constraints/geometric/coincident": ("Hace coincidir dos puntos.", "Makes two points coincide.", "Faz dois pontos coincidirem.", "sk2pts"),
    "workbench/sketcher/constraints/geometric/coincidentunified": ("Coincidencia automática sobre varios puntos.", "Automatic coincidence over several points.", "Coincidência automática sobre vários pontos.", "sk2pts"),
    "workbench/sketcher/constraints/geometric/lock": ("Fija un punto en coordenadas absolutas.", "Locks a point at absolute coordinates.", "Fixa um ponto em coordenadas absolutas.", "skpt"),
    "workbench/sketcher/constraints/geometric/pointonobject": ("Obliga un punto a estar sobre una línea o curva.", "Forces a point to lie on a line or curve.", "Obriga um ponto a ficar sobre uma linha ou curva.", "skptline"),
    "workbench/sketcher/constraints/geometric/horizontal": ("Fuerza una línea a ser horizontal.", "Forces a line to be horizontal.", "Força uma linha a ser horizontal.", "skline"),
    "workbench/sketcher/constraints/geometric/vertical": ("Fuerza una línea a ser vertical.", "Forces a line to be vertical.", "Força uma linha a ser vertical.", "skline"),
    "workbench/sketcher/constraints/geometric/horver": ("Aplica horizontal o vertical según la inclinación.", "Applies horizontal or vertical depending on the slope.", "Aplica horizontal ou vertical conforme a inclinação.", "skline"),
    "workbench/sketcher/constraints/geometric/parallel": ("Hace paralelas dos o más líneas.", "Makes two or more lines parallel.", "Faz duas ou mais linhas paralelas.", "sk2lines"),
    "workbench/sketcher/constraints/geometric/perpendicular": ("Hace perpendiculares dos líneas (90°).", "Makes two lines perpendicular (90°).", "Faz duas linhas perpendiculares (90°).", "sk2lines"),
    "workbench/sketcher/constraints/geometric/tangent": ("Hace tangentes dos curvas, o una curva y una línea.", "Makes two curves, or a curve and a line, tangent.", "Faz duas curvas, ou uma curva e uma linha, tangentes.", "sk2curves"),
    "workbench/sketcher/constraints/geometric/equal": ("Iguala la longitud o el radio de dos entidades.", "Equalizes the length or radius of two entities.", "Iguala o comprimento ou o raio de duas entidades.", "sk2curves"),
    "workbench/sketcher/constraints/geometric/symmetric": ("Hace simétricos dos puntos respecto de una línea o punto.", "Makes two points symmetric about a line or point.", "Faz dois pontos simétricos em relação a uma linha ou ponto.", "sk2pts"),
    "workbench/sketcher/constraints/geometric/block": ("Bloquea la geometría en su posición actual.", "Locks the geometry in its current position.", "Bloqueia a geometria na sua posição atual.", "skgeom"),
    "workbench/sketcher/constraints/geometric/toggledriving": ("Alterna entre restricción conductora y de referencia.", "Toggles between driving and reference constraint.", "Alterna entre restrição condutora e de referência.", "skconstraint"),
    "workbench/sketcher/constraints/geometric/toggleactive": ("Activa o desactiva las restricciones seleccionadas.", "Enables or disables the selected constraints.", "Ativa ou desativa as restrições selecionadas.", "skconstraint"),
    "workbench/sketcher/external": ("Geometría externa de otras piezas.", "External geometry from other parts.", "Geometria externa de outras peças.", "skext"),
    "workbench/sketcher/external/projection": ("Proyecta una arista externa sobre el croquis.", "Projects an external edge onto the sketch.", "Projeta uma aresta externa sobre o croqui."),
    "workbench/sketcher/external/intersection": ("Intersecta la geometría externa con el croquis.", "Intersects external geometry with the sketch.", "Intersecta a geometria externa com o croqui."),
    "workbench/sketcher/oblong": ("Oblongos.", "Oblongs.", "Oblongos."),
    "workbench/sketcher/oblong/create": ("Oblongo (cápsula) por los dos centros y el radio.", "Oblong (capsule) by the two centers and radius.", "Oblongo (cápsula) pelos dois centros e o raio."),
    "workbench/sketcher/point": ("Puntos.", "Points.", "Pontos."),
    "workbench/sketcher/point/create": ("Crea un punto del croquis.", "Creates a sketch point.", "Cria um ponto do croqui."),
    "workbench/sketcher/point/create_by_coords": ("Punto con las coordenadas X, Y dictadas.", "Point with the dictated X, Y coordinates.", "Ponto com as coordenadas X, Y ditadas."),
    "workbench/sketcher/root/root": ("Selecciona el punto raíz (origen) del croquis.", "Selects the sketch root point (origin).", "Seleciona o ponto raiz (origem) do croqui."),
    "workbench/sketcher/select": ("Selecciona los ejes y el origen del croquis.", "Selects the sketch axes and origin.", "Seleciona os eixos e a origem do croqui."),
    "workbench/sketcher/select/horizontal": ("Selecciona el eje horizontal X.", "Selects the horizontal X axis.", "Seleciona o eixo horizontal X."),
    "workbench/sketcher/select/vertical": ("Selecciona el eje vertical Y.", "Selects the vertical Y axis.", "Seleciona o eixo vertical Y."),
    "workbench/sketcher/select/origin": ("Selecciona el origen (0, 0).", "Selects the origin (0, 0).", "Seleciona a origem (0, 0)."),
    "workbench/sketcher/slot": ("Ranuras (ojales).", "Slots.", "Ranhuras (rasgos)."),
    "workbench/sketcher/slot/create": ("Ranura de dos arcos y dos líneas paralelas.", "Slot made of two arcs and two parallel lines.", "Ranhura de dois arcos e duas linhas paralelas."),
    "workbench/sketcher/square": ("Cuadrados.", "Squares.", "Quadrados."),
    "workbench/sketcher/square/create": ("Cuadrado alineado a los ejes por centro y radio.", "Axis-aligned square by center and radius.", "Quadrado alinhado aos eixos por centro e raio."),
    "workbench/sketcher/text": ("Texto en el croquis.", "Text in the sketch.", "Texto no croqui."),
    "workbench/sketcher/text/shapestring": ("Crea una forma de texto en el croquis.", "Creates a text shape in the sketch.", "Cria uma forma de texto no croqui."),
    "workbench/sketcher/tools": ("Cerrar, limpiar, fusionar y reorientar croquis.", "Close, clear, merge and reorient sketches.", "Fechar, limpar, mesclar e reorientar croquis."),
    "workbench/sketcher/tools/leave": ("Cierra el croquis en edición conservando el dibujo.", "Closes the sketch being edited, keeping the drawing.", "Fecha o croqui em edição mantendo o desenho."),
    "workbench/sketcher/tools/deleteconstraints": ("Elimina todas las restricciones del croquis.", "Removes every constraint of the sketch.", "Remove todas as restrições do croqui."),
    "workbench/sketcher/tools/deletegeometry": ("Borra toda la geometría y las restricciones del croquis.", "Deletes all geometry and constraints of the sketch.", "Apaga toda a geometria e as restrições do croqui."),
    "workbench/sketcher/tools/merge": ("Une la geometría de varios croquis en uno.", "Merges the geometry of several sketches into one.", "Une a geometria de vários croquis em um.", "sk2sel"),
    "workbench/sketcher/tools/reorient": ("Reorienta el croquis seleccionado a otra cara.", "Reorients the selected sketch to another face.", "Reorienta o croqui selecionado para outra face.", "sksel"),
    "workbench/sketcher/tools/removeaxes": ("Quita la alineación automática a los ejes.", "Removes the automatic axis alignment.", "Remove o alinhamento automático aos eixos.", "sksel"),
    "workbench/sketcher/validate": ("Validación del croquis.", "Sketch validation.", "Validação do croqui."),
    "workbench/sketcher/validate/validate": ("Revisa el croquis, detecta coincidencias faltantes y repara tolerancias.", "Checks the sketch, finds missing coincidences and fixes tolerances.", "Revisa o croqui, detecta coincidências faltantes e repara tolerâncias."),
    "workbench/sketcher/view": ("Vistas del croquis.", "Sketch views.", "Vistas do croqui."),
    "workbench/sketcher/view/sketch": ("Orienta la cámara perpendicular al croquis.", "Orients the camera perpendicular to the sketch.", "Orienta a câmera perpendicular ao croqui."),
    "workbench/sketcher/view/section": ("Alterna la vista de sección del croquis.", "Toggles the sketch's section view.", "Alterna a vista de seção do croqui."),
    "workbench/sketcher/image": ("Coloca una imagen detrás del croquis para calcarla.", "Places an image behind the sketch to trace it.", "Coloca uma imagem atrás do croqui para decalcá-la.", "none"),
    "workbench/sketcher/new": ("Crea un croquis nuevo.", "Creates a new sketch.", "Cria um croqui novo.", "doc"),
    "workbench/sketcher/leave": ("Cierra el croquis en edición conservando el dibujo.", "Closes the sketch being edited, keeping the drawing.", "Fecha o croqui em edição mantendo o desenho."),
    "workbench/sketcher/edit": ("Edita el croquis seleccionado.", "Edits the selected sketch.", "Edita o croqui selecionado.", "sksel"),
    "workbench/sketcher/attach": ("Adjunta o mapea el croquis seleccionado.", "Attaches or maps the selected sketch.", "Anexa ou mapeia o croqui selecionado.", "sksel"),
    "workbench/sketcher/grid": ("Muestra u oculta la cuadrícula.", "Shows or hides the grid.", "Mostra ou oculta a grade."),
    "workbench/sketcher/cancelediting": ("Sale de la edición cancelando los cambios.", "Leaves editing, canceling the changes.", "Sai da edição cancelando as alterações."),
    "workbench/sketcher/carboncopy": ("Copia la geometría de otro croquis en el activo.", "Copies the geometry of another sketch into the active one.", "Copia a geometria de outro croqui no ativo."),
    "workbench/sketcher/copyelements": ("Copia los elementos seleccionados al portapapeles.", "Copies the selected elements to the clipboard.", "Copia os elementos selecionados para a área de transferência.", "skgeom"),
    "workbench/sketcher/cutelements": ("Corta los elementos seleccionados.", "Cuts the selected elements.", "Corta os elementos selecionados.", "skgeom"),
    "workbench/sketcher/pasteelements": ("Pega los elementos del portapapeles en el croquis.", "Pastes the clipboard elements into the sketch.", "Cola os elementos da área de transferência no croqui."),
    "workbench/sketcher/mirror": ("Refleja los elementos seleccionados respecto de una línea o eje.", "Mirrors the selected elements about a line or axis.", "Reflete os elementos selecionados em relação a uma linha ou eixo.", "skgeom"),
    "workbench/sketcher/mirrorsketch": ("Refleja todo el croquis respecto de los ejes principales.", "Mirrors the whole sketch about the main axes.", "Reflete todo o croqui em relação aos eixos principais."),
    "workbench/sketcher/offset": ("Crea geometría paralela a una distancia de lo seleccionado.", "Creates geometry parallel at a distance from the selection.", "Cria geometria paralela a uma distância da seleção.", "skgeom"),
    "workbench/sketcher/movearray": ("Mueve o copia en matriz la geometría seleccionada.", "Moves or array-copies the selected geometry.", "Move ou copia em matriz a geometria selecionada.", "skgeom"),
    "workbench/sketcher/rotatepolar": ("Rota o copia en forma polar la geometría seleccionada.", "Rotates or polar-copies the selected geometry.", "Rotaciona ou copia em forma polar a geometria selecionada.", "skgeom"),
    "workbench/sketcher/scale": ("Cambia la escala de la geometría seleccionada.", "Changes the scale of the selected geometry.", "Altera a escala da geometria selecionada.", "skgeom"),
    "workbench/sketcher/trimedge": ("Recorta una arista usando otra geometría como límite.", "Trims an edge using other geometry as the limit.", "Apara uma aresta usando outra geometria como limite."),
    "workbench/sketcher/splitedge": ("Divide una arista en dos en el punto elegido.", "Splits an edge in two at the chosen point.", "Divide uma aresta em duas no ponto escolhido."),
    "workbench/sketcher/extendedge": ("Extiende una arista hasta otra geometría.", "Extends an edge up to other geometry.", "Estende uma aresta até outra geometria."),
    "workbench/sketcher/fillet": ("Crea un redondeo entre dos aristas adyacentes.", "Creates a fillet between two adjacent edges.", "Cria um arredondamento entre duas arestas adjacentes."),
    "workbench/sketcher/chamfer": ("Crea un chaflán entre dos aristas adyacentes.", "Creates a chamfer between two adjacent edges.", "Cria um chanfro entre duas arestas adjacentes."),
}
