"""Descripciones del manual: Assembly, Draft y Part (ver desc_explorer.py para el formato)."""

G = {
    "workbench/assembly": "asm",
    "workbench/draft": "plane",
    "workbench/part": "doc",
}

D = {
    # --------------------------------------------------------------- Assembly
    "workbench/assembly": ("Ensamblajes mecánicos: piezas, juntas, simulación y lista de materiales.",
                           "Mechanical assemblies: parts, joints, simulation and bill of materials.",
                           "Montagens mecânicas: peças, juntas, simulação e lista de materiais."),
    "workbench/assembly/joint": ("Juntas que relacionan dos piezas por caras, aristas o puntos.",
                                 "Joints that relate two parts by faces, edges or points.",
                                 "Juntas que relacionam duas peças por faces, arestas ou pontos.", "asm2"),
    "workbench/assembly/joint/angle": ("Fija el ángulo entre dos piezas.", "Sets the angle between two parts.", "Fixa o ângulo entre duas peças."),
    "workbench/assembly/joint/ball": ("Junta esférica (rótula): las piezas giran libremente sobre un punto.", "Ball joint: the parts rotate freely about a point.", "Junta esférica (rótula): as peças giram livremente em torno de um ponto."),
    "workbench/assembly/joint/parallel": ("Mantiene dos piezas paralelas.", "Keeps two parts parallel.", "Mantém duas peças paralelas."),
    "workbench/assembly/joint/perpendicular": ("Mantiene dos piezas perpendiculares.", "Keeps two parts perpendicular.", "Mantém duas peças perpendiculares."),
    "workbench/assembly/joint/belt": ("Junta de correa entre dos poleas.", "Belt joint between two pulleys.", "Junta de correia entre duas polias."),
    "workbench/assembly/joint/gears": ("Junta de engranajes entre dos ruedas dentadas.", "Gear joint between two gear wheels.", "Junta de engrenagens entre duas rodas dentadas."),
    "workbench/assembly/joint/rackpinion": ("Junta de piñón y cremallera.", "Rack-and-pinion joint.", "Junta de pinhão e cremalheira."),
    "workbench/assembly/joint/screw": ("Junta helicoidal (tornillo): giro y avance ligados.", "Screw joint: rotation and advance are linked.", "Junta helicoidal (parafuso): giro e avanço ligados."),
    "workbench/assembly/joint/cylindrical": ("Junta cilíndrica: giro y deslizamiento sobre un mismo eje.", "Cylindrical joint: rotation and sliding on the same axis.", "Junta cilíndrica: giro e deslizamento no mesmo eixo."),
    "workbench/assembly/joint/distance": ("Fija la distancia entre dos piezas.", "Sets the distance between two parts.", "Fixa a distância entre duas peças."),
    "workbench/assembly/joint/fixed": ("Junta fija: las dos piezas quedan rígidamente unidas.", "Fixed joint: the two parts are rigidly attached.", "Junta fixa: as duas peças ficam rigidamente unidas."),
    "workbench/assembly/joint/revolute": ("Junta de revolución (bisagra): giro sobre un eje.", "Revolute joint (hinge): rotation about one axis.", "Junta de revolução (dobradiça): giro em torno de um eixo."),
    "workbench/assembly/joint/slider": ("Junta deslizante: una pieza se desliza sobre un eje.", "Slider joint: one part slides along an axis.", "Junta deslizante: uma peça desliza sobre um eixo."),
    "workbench/assembly/create": ("Crea un ensamblaje nuevo.", "Creates a new assembly.", "Cria uma montagem nova.", "doc"),
    "workbench/assembly/newpart": ("Crea una pieza nueva dentro del ensamblaje.", "Creates a new part inside the assembly.", "Cria uma peça nova dentro da montagem."),
    "workbench/assembly/link": ("Inserta como vínculo un componente existente del documento.", "Inserts an existing document component as a link.", "Insere como vínculo um componente existente do documento."),
    "workbench/assembly/solve": ("Resuelve el ensamblaje y aplica todas las juntas.", "Solves the assembly and applies every joint.", "Resolve a montagem e aplica todas as juntas."),
    "workbench/assembly/view": ("Crea la vista explosionada del ensamblaje.", "Creates the assembly's exploded view.", "Cria a vista explodida da montagem."),
    "workbench/assembly/simulation": ("Crea una simulación de movimiento del ensamblaje.", "Creates a motion simulation of the assembly.", "Cria uma simulação de movimento da montagem.", "asm2"),
    "workbench/assembly/bom": ("Genera la lista de materiales (BOM) del ensamblaje.", "Generates the assembly's bill of materials (BOM).", "Gera a lista de materiais (BOM) da montagem."),
    "workbench/assembly/preferences": ("Abre las preferencias del banco de ensamblaje.", "Opens the Assembly workbench preferences.", "Abre as preferências da bancada de montagem.", "none"),
    "workbench/assembly/grounded": ("Ancla una pieza para que no se mueva.", "Grounds a part so it does not move.", "Ancora uma peça para que não se mova."),
    "workbench/assembly/fixed_joint": ("Une dos piezas con una junta fija.", "Joins two parts with a fixed joint.", "Une duas peças com uma junta fixa.", "asm2"),
    "workbench/assembly/revolute_joint": ("Une dos piezas con una bisagra (junta giratoria).", "Joins two parts with a hinge (revolute joint).", "Une duas peças com uma dobradiça (junta giratória).", "asm2"),
    "workbench/assembly/slider_joint": ("Une dos piezas con una junta deslizante.", "Joins two parts with a slider joint.", "Une duas peças com uma junta deslizante.", "asm2"),
    "workbench/assembly/distance_joint": ("Une dos piezas manteniendo una distancia.", "Joins two parts keeping a distance.", "Une duas peças mantendo uma distância.", "asm2"),
    "workbench/assembly/angle_joint": ("Une dos piezas manteniendo un ángulo.", "Joins two parts keeping an angle.", "Une duas peças mantendo um ângulo.", "asm2"),
    "workbench/assembly/ground_part": ("Ancla la pieza elegida (por ejemplo, el perno).", "Grounds the chosen part (for example, the bolt).", "Ancora a peça escolhida (por exemplo, o parafuso).", "asm"),
    "workbench/assembly/ball_joint": ("Une dos piezas con una rótula.", "Joins two parts with a ball joint.", "Une duas peças com uma rótula.", "asm2"),
    "workbench/assembly/cylindrical_joint": ("Une dos piezas por sus cilindros (giro y deslizamiento en el eje).", "Joins two parts by their cylinders (rotation and sliding on the axis).", "Une duas peças pelos seus cilindros (giro e deslizamento no eixo).", "asm2"),
    "workbench/assembly/parallel_joint": ("Mantiene dos piezas paralelas.", "Keeps two parts parallel.", "Mantém duas peças paralelas.", "asm2"),
    "workbench/assembly/perpendicular_joint": ("Mantiene dos piezas perpendiculares.", "Keeps two parts perpendicular.", "Mantém duas peças perpendiculares.", "asm2"),
    "workbench/assembly/gears_joint": ("Engrana dos piezas.", "Meshes two parts as gears.", "Engrena duas peças.", "asm2"),
    "workbench/assembly/belt_joint": ("Conecta dos piezas con una correa.", "Connects two parts with a belt.", "Conecta duas peças com uma correia.", "asm2"),
    "workbench/assembly/screw_joint": ("Une dos piezas con una junta de tornillo.", "Joins two parts with a screw joint.", "Une duas peças com uma junta de parafuso.", "asm2"),
    "workbench/assembly/rack_pinion_joint": ("Une dos piezas como cremallera y piñón.", "Joins two parts as rack and pinion.", "Une duas peças como cremalheira e pinhão.", "asm2"),

    # ------------------------------------------------------------------ Draft
    "workbench/draft": ("Dibujo 2D: formas, curvas, anotaciones y modificaciones.",
                        "2D drafting: shapes, curves, annotations and modifications.",
                        "Desenho 2D: formas, curvas, anotações e modificações."),
    "workbench/draft/annotation": ("Textos y etiquetas.", "Texts and labels.", "Textos e etiquetas."),
    "workbench/draft/annotation/text": ("Inserta un texto 2D en el plano de trabajo.", "Inserts 2D text on the working plane.", "Insere um texto 2D no plano de trabalho."),
    "workbench/draft/annotation/shapestring": ("Crea una forma plana a partir de texto y una tipografía.", "Creates a flat shape from text and a font.", "Cria uma forma plana a partir de texto e uma fonte.", "docfont"),
    "workbench/draft/annotation/label": ("Crea una etiqueta con línea directriz.", "Creates a label with a leader line.", "Cria uma etiqueta com linha de chamada."),
    "workbench/draft/annotation_style_editor": ("Estilos de anotación.", "Annotation styles.", "Estilos de anotação."),
    "workbench/draft/annotation_style_editor/editor": ("Abre el editor de estilos de texto, cotas y etiquetas.", "Opens the text, dimension and label style editor.", "Abre o editor de estilos de texto, cotas e etiquetas.", "doc"),
    "workbench/draft/arc": ("Arcos de circunferencia.", "Circular arcs.", "Arcos de circunferência."),
    "workbench/draft/arc/center": ("Arco por centro, radio y ángulos.", "Arc by center, radius and angles.", "Arco por centro, raio e ângulos."),
    "workbench/draft/arc/points": ("Arco que pasa por tres puntos.", "Arc through three points.", "Arco que passa por três pontos."),
    "workbench/draft/curve": ("Curvas suaves.", "Smooth curves.", "Curvas suaves."),
    "workbench/draft/curve/bezier": ("Curva de Bézier de grado N.", "Degree-N Bézier curve.", "Curva de Bézier de grau N."),
    "workbench/draft/curve/bspline": ("Curva B-Spline que sigue los puntos dados.", "B-Spline curve following the given points.", "Curva B-Spline que segue os pontos dados."),
    "workbench/draft/curve/cubic": ("Curva de Bézier cúbica.", "Cubic Bézier curve.", "Curva de Bézier cúbica."),
    "workbench/draft/circle": ("Círculos.", "Circles.", "Círculos."),
    "workbench/draft/circle/center": ("Círculo por centro y radio.", "Circle by center and radius.", "Círculo por centro e raio."),
    "workbench/draft/array": ("Matrices: repetir un objeto en un patrón.", "Arrays: repeat an object in a pattern.", "Matrizes: repetir um objeto em um padrão.", "sel"),
    "workbench/draft/array/circular": ("Matriz circular: copias en anillos concéntricos.", "Circular array: copies in concentric rings.", "Matriz circular: cópias em anéis concêntricos."),
    "workbench/draft/array/ortho": ("Matriz ortogonal: filas y columnas.", "Orthogonal array: rows and columns.", "Matriz ortogonal: linhas e colunas."),
    "workbench/draft/array/polar": ("Matriz polar: copias alrededor de un centro.", "Polar array: copies around a center.", "Matriz polar: cópias ao redor de um centro."),
    "workbench/draft/array/path": ("Matriz a lo largo de una trayectoria.", "Array along a path.", "Matriz ao longo de uma trajetória.", "selpath"),
    "workbench/draft/array/pathlink": ("Matriz sobre trayectoria con vínculos (más liviana).", "Path array made of links (lighter).", "Matriz sobre trajetória com vínculos (mais leve).", "selpath"),
    "workbench/draft/array/point": ("Matriz que coloca copias en puntos dados.", "Array placing copies at given points.", "Matriz que coloca cópias em pontos dados.", "selpoint"),
    "workbench/draft/array/pointlink": ("Matriz de puntos con vínculos.", "Point array made of links.", "Matriz de pontos com vínculos.", "selpoint"),
    "workbench/draft/modify": ("Operaciones sobre figuras existentes.", "Operations on existing shapes.", "Operações sobre figuras existentes.", "sel"),
    "workbench/draft/modify/clone": ("Hace una copia vinculada: si el original cambia, el clon también.", "Makes a linked copy: if the original changes, so does the clone.", "Faz uma cópia vinculada: se o original muda, o clone também."),
    "workbench/draft/modify/downgrade": ("Simplifica una figura (por ejemplo, separa una cara en líneas).", "Simplifies a shape (for example, splits a face into lines).", "Simplifica uma figura (por exemplo, separa uma face em linhas)."),
    "workbench/draft/modify/sketch": ("Convierte una figura de Draft en un croquis, o al revés.", "Converts a Draft shape into a sketch, or back.", "Converte uma figura do Draft em croqui, ou o contrário."),
    "workbench/draft/modify/edit": ("Entra al modo edición para mover los puntos de la figura.", "Enters edit mode to move the shape's points.", "Entra no modo de edição para mover os pontos da figura."),
    "workbench/draft/modify/fillet": ("Crea un redondeo entre dos líneas o segmentos.", "Creates a fillet between two lines or segments.", "Cria um arredondamento entre duas linhas ou segmentos."),
    "workbench/draft/modify/join": ("Une dos o más líneas en un solo objeto.", "Joins two or more lines into a single object.", "Une duas ou mais linhas em um único objeto."),
    "workbench/draft/modify/cut": ("Corta un objeto con otro: al primero le quita la parte del segundo.", "Cuts one object with another: removes from the first the part the second occupies.", "Corta um objeto com outro: remove do primeiro a parte ocupada pelo segundo.", "sel2"),
    "workbench/draft/modify/move": ("Mueve o copia objetos a una nueva posición.", "Moves or copies objects to a new position.", "Move ou copia objetos para uma nova posição."),
    "workbench/draft/modify/offset": ("Crea una copia paralela a una distancia dada.", "Creates a parallel copy at a given distance.", "Cria uma cópia paralela a uma distância dada."),
    "workbench/draft/modify/rotate": ("Rota o copia objetos alrededor de un centro.", "Rotates or copies objects around a center.", "Rotaciona ou copia objetos ao redor de um centro."),
    "workbench/draft/modify/mirror": ("Crea la copia simétrica respecto de una línea.", "Creates the mirrored copy about a line.", "Cria a cópia simétrica em relação a uma linha."),
    "workbench/draft/dimension": ("Cotas de Draft.", "Draft dimensions.", "Cotas do Draft."),
    "workbench/draft/dimension/linear": ("Crea una cota lineal con su medida.", "Creates a linear dimension with its measurement.", "Cria uma cota linear com a sua medida."),
    "workbench/draft/dimension/flip": ("Invierte el texto de la cota girándolo 180°.", "Flips the dimension text by rotating it 180°.", "Inverte o texto da cota girando-o 180°.", "dimsel"),
    "workbench/draft/ellipse": ("Elipses.", "Ellipses.", "Elipses."),
    "workbench/draft/ellipse/center": ("Elipse por radios mayor y menor.", "Ellipse by major and minor radii.", "Elipse por raios maior e menor."),
    "workbench/draft/facebinder": ("Superficies a partir de caras.", "Surfaces from faces.", "Superfícies a partir de faces."),
    "workbench/draft/facebinder/create": ("Crea una superficie a partir de las caras seleccionadas.", "Creates a surface from the selected faces.", "Cria uma superfície a partir das faces selecionadas.", "selface"),
    "workbench/draft/drafting": ("Líneas y polilíneas.", "Lines and polylines.", "Linhas e polilinhas."),
    "workbench/draft/drafting/wire": ("Dibuja una polilínea de varios segmentos.", "Draws a multi-segment polyline.", "Desenha uma polilinha de vários segmentos."),
    "workbench/draft/drafting/line": ("Dibuja una línea recta, también «línea por puntos».", "Draws a straight line, also «line by points».", "Desenha uma linha reta, também «linha por pontos»."),
    "workbench/draft/creation": ("Figuras básicas: punto, polígono, rectángulo, triángulo y sombreado.", "Basic shapes: point, polygon, rectangle, triangle and hatch.", "Figuras básicas: ponto, polígono, retângulo, triângulo e hachura."),
    "workbench/draft/creation/hatch": ("Rellena una figura con un patrón.", "Fills a shape with a pattern.", "Preenche uma figura com um padrão.", "sel"),
    "workbench/draft/creation/point": ("Marca un punto en las coordenadas dictadas.", "Marks a point at the dictated coordinates.", "Marca um ponto nas coordenadas ditadas."),
    "workbench/draft/creation/polygon": ("Dibuja un polígono regular.", "Draws a regular polygon.", "Desenha um polígono regular."),
    "workbench/draft/creation/rectangle": ("Dibuja un rectángulo por dos esquinas.", "Draws a rectangle by two corners.", "Desenha um retângulo por dois cantos."),
    "workbench/draft/creation/rectangle_center": ("Dibuja un rectángulo por su centro y su tamaño.", "Draws a rectangle by its center and size.", "Desenha um retângulo pelo seu centro e tamanho."),
    "workbench/draft/creation/triangle": ("Dibuja un triángulo por sus tres vértices.", "Draws a triangle by its three vertices.", "Desenha um triângulo pelos seus três vértices."),
    "workbench/draft/modification": ("Más operaciones sobre figuras existentes.", "More operations on existing shapes.", "Mais operações sobre figuras existentes.", "sel"),
    "workbench/draft/modification/scale": ("Aumenta o reduce el tamaño proporcionalmente.", "Enlarges or shrinks proportionally.", "Aumenta ou reduz o tamanho proporcionalmente."),
    "workbench/draft/modification/shape_2d_view": ("Genera una proyección 2D plana de un objeto 3D.", "Generates a flat 2D projection of a 3D object.", "Gera uma projeção 2D plana de um objeto 3D."),
    "workbench/draft/modification/slope": ("Cambia la pendiente (inclinación en Z) de un alambre.", "Changes the slope (Z inclination) of a wire.", "Altera a inclinação (em Z) de um arame."),
    "workbench/draft/modification/split": ("Parte una línea o alambre en un punto.", "Splits a line or wire at a point.", "Divide uma linha ou arame em um ponto."),
    "workbench/draft/modification/stretch": ("Estira la geometría desplazando un conjunto de vértices.", "Stretches geometry by moving a set of vertices.", "Estica a geometria deslocando um conjunto de vértices."),
    "workbench/draft/modification/subelement_highlight": ("Resalta caras, aristas o vértices de la selección.", "Highlights faces, edges or vertices of the selection.", "Destaca faces, arestas ou vértices da seleção."),
    "workbench/draft/modification/trimex": ("Recorta o extiende una entidad hasta otra.", "Trims or extends an entity up to another.", "Apara ou estende uma entidade até outra."),
    "workbench/draft/modification/upgrade": ("Promueve elementos simples a caras o sólidos.", "Promotes simple elements to faces or solids.", "Promove elementos simples a faces ou sólidos."),
    "workbench/draft/modification/wire_to_bspline": ("Convierte una polilínea en una curva B-Spline suave.", "Converts a polyline into a smooth B-Spline curve.", "Converte uma polilinha em uma curva B-Spline suave."),
    "workbench/draft/pointplacement": ("Colocación de puntos de referencia.", "Placing reference points.", "Colocação de pontos de referência.", "doc"),
    "workbench/draft/pointplacement/addpoint": ("Coloca un punto en el vértice seleccionado.", "Places a point at the selected vertex.", "Coloca um ponto no vértice selecionado.", "selvertex"),
    "workbench/draft/pointplacement/pointatvertex": ("Inserta un punto en el índice de vértice indicado.", "Inserts a point at the given vertex index.", "Insere um ponto no índice de vértice indicado.", "selvertex"),
    "workbench/draft/pointplacement/midpoint": ("Coloca un punto en el centro de la arista seleccionada.", "Places a point at the middle of the selected edge.", "Coloca um ponto no centro da aresta selecionada.", "seledge"),
    "workbench/draft/pointplacement/pointatcoords": ("Crea un punto en coordenadas X, Y, Z exactas.", "Creates a point at exact X, Y, Z coordinates.", "Cria um ponto em coordenadas X, Y, Z exatas."),
    "workbench/draft/pointconnect": ("Conectar puntos para formar líneas y polígonos.", "Connect points to form lines and polygons.", "Conectar pontos para formar linhas e polígonos.", "selpoint"),
    "workbench/draft/pointconnect/connect": ("Conecta los puntos seleccionados.", "Connects the selected points.", "Conecta os pontos selecionados."),
    "workbench/draft/pointconnect/createline": ("Crea una línea entre los puntos.", "Creates a line between the points.", "Cria uma linha entre os pontos."),
    "workbench/draft/pointconnect/closewire": ("Cierra el alambre uniendo el último punto con el primero.", "Closes the wire joining the last point to the first.", "Fecha o arame unindo o último ponto ao primeiro."),
    "workbench/draft/pointconnect/createpolygon": ("Crea un polígono con los puntos.", "Creates a polygon from the points.", "Cria um polígono com os pontos."),
    "workbench/draft/image": ("Coloca una imagen de referencia en el plano XY, XZ o YZ.", "Places a reference image on the XY, XZ or YZ plane.", "Coloca uma imagem de referência no plano XY, XZ ou YZ."),

    # ------------------------------------------------------------------- Part
    "workbench/part": ("Sólidos, primitivas y operaciones booleanas y de superficie.",
                       "Solids, primitives and boolean and surface operations.",
                       "Sólidos, primitivas e operações booleanas e de superfície."),
    "workbench/part/box": ("Caja primitiva.", "Primitive box.", "Caixa primitiva."),
    "workbench/part/box/box": ("Crea una caja paramétrica (10 × 10 × 10 mm por defecto).", "Creates a parametric box (10 × 10 × 10 mm by default).", "Cria uma caixa paramétrica (10 × 10 × 10 mm por padrão)."),
    "workbench/part/circle/circle": ("Crea un círculo o arco como arista (no es un sólido).", "Creates a circle or arc as an edge (not a solid).", "Cria um círculo ou arco como aresta (não é um sólido)."),
    "workbench/part/cone/cone": ("Crea un cono o tronco de cono primitivo.", "Creates a primitive cone or truncated cone.", "Cria um cone ou tronco de cone primitivo."),
    "workbench/part/cube/cube": ("Crea un cubo sólido paramétrico (10 × 10 × 10 mm).", "Creates a parametric solid cube (10 × 10 × 10 mm).", "Cria um cubo sólido paramétrico (10 × 10 × 10 mm)."),
    "workbench/part/cylinder/cylinder": ("Crea un cilindro paramétrico (radio 2 mm, alto 10 mm).", "Creates a parametric cylinder (radius 2 mm, height 10 mm).", "Cria um cilindro paramétrico (raio 2 mm, altura 10 mm)."),
    "workbench/part/ellipse/ellipse": ("Crea una elipse o arco elíptico como arista.", "Creates an ellipse or elliptical arc as an edge.", "Cria uma elipse ou arco elíptico como aresta."),
    "workbench/part/line/line": ("Crea un segmento recto entre dos puntos 3D.", "Creates a straight segment between two 3D points.", "Cria um segmento reto entre dois pontos 3D."),
    "workbench/part/new_sketch/new sketch": ("Crea un croquis nuevo sobre un plano o una cara.", "Creates a new sketch on a plane or a face.", "Cria um croqui novo sobre um plano ou uma face."),
    "workbench/part/chamfer/chaflan": ("Aplica un chaflán a las aristas seleccionadas.", "Applies a chamfer to the selected edges.", "Aplica um chanfro às arestas selecionadas.", "seledge"),
    "workbench/part/color_per_face/paint face": ("Pinta cada cara del objeto con un color distinto.", "Paints each face of the object a different color.", "Pinta cada face do objeto com uma cor diferente.", "selpart"),
    "workbench/part/cross_sections/secciones transversales": ("Genera secciones transversales del objeto.", "Generates cross sections of the object.", "Gera seções transversais do objeto.", "selpart"),
    "workbench/part/extrude/extruir": ("Extruye un perfil y crea un sólido.", "Extrudes a profile and creates a solid.", "Extrude um perfil e cria um sólido.", "selprofile"),
    "workbench/part/fillet/redondear bordes": ("Redondea las aristas seleccionadas.", "Rounds the selected edges.", "Arredonda as arestas selecionadas.", "seledge"),
    "workbench/part/loft/hacer loft": ("Crea un sólido o superficie entre varios perfiles (loft).", "Creates a solid or surface between several profiles (loft).", "Cria um sólido ou superfície entre vários perfis (loft).", "selprofiles"),
    "workbench/part/makeface/makeface": ("Convierte un contorno cerrado en una cara.", "Turns a closed outline into a face.", "Converte um contorno fechado em uma face.", "selprofile"),
    "workbench/part/makeface/upgrade": ("Convierte un alambre cerrado en cara automáticamente.", "Automatically converts a closed wire into a face.", "Converte automaticamente um arame fechado em uma face.", "selprofile"),
    "workbench/part/mirror/espejo": ("Crea la copia simétrica del objeto respecto de un plano.", "Creates the mirrored copy of the object about a plane.", "Cria a cópia simétrica do objeto em relação a um plano.", "selpart"),
    "workbench/part/offset/desfase": ("Engrosca o desplaza el objeto 1,0 mm en 3D.", "Thickens or offsets the object 1.0 mm in 3D.", "Engrossa ou desloca o objeto 1,0 mm em 3D.", "selpart"),
    "workbench/part/offset2d/contorno": ("Desplaza 1,0 mm un contorno o cara plana.", "Offsets a flat wire or face by 1.0 mm.", "Desloca 1,0 mm um contorno ou face plana.", "selwire"),
    "workbench/part/projection_on_surface/proyectar dibujo": ("Proyecta formas sobre una superficie de apoyo.", "Projects shapes onto a support surface.", "Projeta formas sobre uma superfície de apoio.", "selsurf"),
    "workbench/part/revolve/revolucion": ("Genera un sólido de revolución de 360° alrededor del eje Z.", "Generates a 360° solid of revolution about the Z axis.", "Gera um sólido de revolução de 360° em torno do eixo Z.", "selprofile"),
    "workbench/part/ruled_surface/superficie reglada": ("Crea una superficie reglada entre dos aristas o curvas.", "Creates a ruled surface between two edges or curves.", "Cria uma superfície regrada entre duas arestas ou curvas.", "sel2edges"),
    "workbench/part/scale/escalar": ("Escala el objeto con un factor uniforme de 2×.", "Scales the object by a uniform factor of 2×.", "Escala o objeto com um fator uniforme de 2×.", "selpart"),
    "workbench/part/section/intersección": ("Calcula la curva de intersección entre dos objetos.", "Computes the intersection curve between two objects.", "Calcula a curva de interseção entre dois objetos.", "sel2part"),
    "workbench/part/sweep/barrer perfil": ("Genera un sólido barriendo un perfil a lo largo de una trayectoria.", "Generates a solid by sweeping a profile along a path.", "Gera um sólido varrendo um perfil ao longo de uma trajetória.", "selsweep"),
}
