"""Descripciones del manual: TechDraw (ver desc_explorer.py para el formato)."""

G = {
    "workbench/techdraw": "techpage",
}

D = {
    "workbench/techdraw": ("Planos técnicos: hojas, vistas, cotas, anotaciones y símbolos.",
                           "Technical drawings: sheets, views, dimensions, annotations and symbols.",
                           "Desenhos técnicos: folhas, vistas, cotas, anotações e símbolos."),
    "workbench/techdraw/views": ("Vistas de proyección, detalle y sección.", "Projection, detail and section views.", "Vistas de projeção, detalhe e seção."),
    "workbench/techdraw/views/view": ("Agrega una vista del objeto seleccionado a la hoja.", "Adds a view of the selected object to the sheet.", "Adiciona uma vista do objeto selecionado à folha.", "techobj"),
    "workbench/techdraw/views/detailview": ("Crea una vista de detalle ampliada de una zona.", "Creates an enlarged detail view of an area.", "Cria uma vista de detalhe ampliada de uma área.", "techview"),
    "workbench/techdraw/views/brokenview": ("Crea una vista interrumpida (acorta una pieza larga).", "Creates a broken view (shortens a long part).", "Cria uma vista interrompida (encurta uma peça longa).", "techview"),
    "workbench/techdraw/views/clipgroup": ("Crea un grupo de recorte para mostrar solo una zona.", "Creates a clip group to show only one area.", "Cria um grupo de recorte para mostrar apenas uma área.", "techpage"),
    "workbench/techdraw/views/complexsection": ("Crea una sección compleja con varios planos de corte.", "Creates a complex section with several cutting planes.", "Cria uma seção complexa com vários planos de corte.", "techview"),
    "workbench/techdraw/views/draft": ("Inserta una vista de objetos de Draft.", "Inserts a view of Draft objects.", "Insere uma vista de objetos do Draft.", "techpage"),
    "workbench/techdraw/views/spreadsheet": ("Inserta una hoja de cálculo como tabla en el plano.", "Inserts a spreadsheet as a table on the drawing.", "Insere uma planilha como tabela no desenho.", "techpage"),
    "workbench/techdraw/views/objectview": ("Crea una vista de un objeto en la hoja eligiéndolo todo por voz: objeto (lista o deletreo), dirección, escala y posición.", "Creates a view of an object on the sheet choosing everything by voice: object (list or spelling), direction, scale and position.", "Cria uma vista de um objeto na folha escolhendo tudo por voz: objeto (lista ou soletração), direção, escala e posição.", "techpage"),
    "workbench/techdraw/views/direction": ("Cambia la dirección de proyección de la vista.", "Changes the projection direction of the view.", "Altera a direção de projeção da vista.", "techview"),
    "workbench/techdraw/views/scale": ("Cambia la escala de la vista.", "Changes the scale of the view.", "Altera a escala da vista.", "techview"),
    "workbench/techdraw/views/position": ("Mueve la vista a otra posición de la hoja.", "Moves the view to another position on the sheet.", "Move a vista para outra posição da folha.", "techview"),
    "workbench/techdraw/views/projection": ("Elige el tipo de proyección de la hoja (primer o tercer ángulo).", "Chooses the sheet's projection type (first or third angle).", "Escolhe o tipo de projeção da folha (primeiro ou terceiro diedro).", "techpage"),
    "workbench/techdraw/dimensions": ("Cotas de longitud, radio, diámetro, ángulo y más.", "Length, radius, diameter, angle and other dimensions.", "Cotas de comprimento, raio, diâmetro, ângulo e mais.", "techview"),
    "workbench/techdraw/dimensions/dimension": ("Cota general.", "General dimension.", "Cota geral."),
    "workbench/techdraw/dimensions/dimension/dimension": ("Agrega una cota según lo seleccionado.", "Adds a dimension based on the selection.", "Adiciona uma cota conforme a seleção."),
    "workbench/techdraw/dimensions/length": ("Cota de longitud.", "Length dimension.", "Cota de comprimento."),
    "workbench/techdraw/dimensions/length/length": ("Acota la longitud de una arista.", "Dimensions the length of an edge.", "Cota o comprimento de uma aresta."),
    "workbench/techdraw/dimensions/horizontal": ("Cota horizontal.", "Horizontal dimension.", "Cota horizontal."),
    "workbench/techdraw/dimensions/horizontal/horizontal": ("Acota la distancia horizontal (ancho).", "Dimensions the horizontal distance (width).", "Cota a distância horizontal (largura)."),
    "workbench/techdraw/dimensions/extent": ("Cotas de extensión total.", "Overall extent dimensions.", "Cotas de extensão total."),
    "workbench/techdraw/dimensions/extent/extent": ("Acota la extensión total de la vista.", "Dimensions the overall extent of the view.", "Cota a extensão total da vista."),
    "workbench/techdraw/dimensions/extent/totals": ("Agrega las cotas totales (ancho y alto) de la vista.", "Adds the overall dimensions (width and height) of the view.", "Adiciona as cotas totais (largura e altura) da vista."),
    "workbench/techdraw/dimensions/radius": ("Cota de radio.", "Radius dimension.", "Cota de raio."),
    "workbench/techdraw/dimensions/radius/radius": ("Acota el radio de un arco o círculo.", "Dimensions the radius of an arc or circle.", "Cota o raio de um arco ou círculo."),
    "workbench/techdraw/dimensions/diameter": ("Cota de diámetro.", "Diameter dimension.", "Cota de diâmetro."),
    "workbench/techdraw/dimensions/diameter/diameter": ("Acota el diámetro de un círculo.", "Dimensions the diameter of a circle.", "Cota o diâmetro de um círculo."),
    "workbench/techdraw/dimensions/angle": ("Cotas de ángulo.", "Angle dimensions.", "Cotas de ângulo."),
    "workbench/techdraw/dimensions/angle/angle": ("Acota el ángulo entre dos líneas.", "Dimensions the angle between two lines.", "Cota o ângulo entre duas linhas."),
    "workbench/techdraw/dimensions/angle/points": ("Acota un ángulo definido por tres puntos.", "Dimensions an angle defined by three points.", "Cota um ângulo definido por três pontos."),
    "workbench/techdraw/dimensions/vertical": ("Acota la distancia vertical (alto).", "Dimensions the vertical distance (height).", "Cota a distância vertical (altura)."),
    "workbench/techdraw/dimensions/area": ("Agrega una cota de área a una cara de la vista.", "Adds an area dimension to a face in the view.", "Adiciona uma cota de área a uma face da vista.", "techface"),
    "workbench/techdraw/dimensions/fit": ("Abre el panel para aplicar un ajuste normalizado ISO 286.", "Opens the panel to apply a standard ISO 286 fit.", "Abre o painel para aplicar um ajuste normalizado ISO 286.", "techdim"),
    "workbench/techdraw/addlines": ("Líneas auxiliares y de centro.", "Auxiliary and center lines.", "Linhas auxiliares e de centro.", "techview"),
    "workbench/techdraw/addlines/twolines": ("Línea central entre dos líneas.", "Center line between two lines.", "Linha central entre duas linhas."),
    "workbench/techdraw/addlines/twopoints": ("Línea central entre dos puntos.", "Center line between two points.", "Linha central entre dois pontos."),
    "workbench/techdraw/addlines/cosmetic": ("Línea cosmética (auxiliar) en la vista.", "Cosmetic (auxiliary) line in the view.", "Linha cosmética (auxiliar) na vista."),
    "workbench/techdraw/addlines/decorate": ("Cambia el estilo de una línea.", "Changes a line's style.", "Altera o estilo de uma linha."),
    "workbench/techdraw/addlines/center": ("Línea de centro de una cara.", "Center line of a face.", "Linha de centro de uma face."),
    "workbench/techdraw/addlines/axis": ("Dibuja el eje de simetría (línea de centro) de una vista elegida por voz.", "Draws the axis of symmetry (center line) of a view chosen by voice.", "Desenha o eixo de simetria (linha de centro) de uma vista escolhida por voz."),
    "workbench/techdraw/symbols": ("Símbolos de soldadura, texto enriquecido y acabado.", "Welding symbols, rich text and surface finish.", "Símbolos de soldagem, texto rico e acabamento.", "techview"),
    "workbench/techdraw/symbols/weldsymbol": ("Inserta un símbolo de soldadura.", "Inserts a welding symbol.", "Insere um símbolo de soldagem."),
    "workbench/techdraw/symbols/richtext": ("Inserta un texto enriquecido.", "Inserts rich text.", "Insere um texto rico."),
    "workbench/techdraw/symbols/finish": ("Inserta el símbolo de acabado superficial.", "Inserts the surface finish symbol.", "Insere o símbolo de acabamento superficial."),
    "workbench/techdraw/snaps": ("Capturas (enganches) a puntos notables.", "Snaps to notable points.", "Capturas (encaixes) a pontos notáveis.", "techview"),
    "workbench/techdraw/snaps/midpoints": ("Captura los puntos medios.", "Snaps to midpoints.", "Captura os pontos médios."),
    "workbench/techdraw/snaps/quadrants": ("Captura los puntos de cuadrante.", "Snaps to quadrant points.", "Captura os pontos de quadrante."),
    "workbench/techdraw/topology": ("Elementos topológicos de la vista.", "Topological elements of the view.", "Elementos topológicos da vista.", "techview"),
    "workbench/techdraw/topology/showAll": ("Muestra todos los elementos topológicos.", "Shows every topological element.", "Mostra todos os elementos topológicos."),
    "workbench/techdraw/page": ("Hojas, plantillas y salidas (imprimir, PDF, DXF, SVG).", "Sheets, templates and outputs (print, PDF, DXF, SVG).", "Folhas, modelos e saídas (imprimir, PDF, DXF, SVG).", "doc"),
    "workbench/techdraw/page/default": ("Crea una hoja con la plantilla por defecto.", "Creates a sheet with the default template.", "Cria uma folha com o modelo padrão."),
    "workbench/techdraw/page/template": ("Crea una hoja con una plantilla elegida.", "Creates a sheet with a chosen template.", "Cria uma folha com um modelo escolhido."),
    "workbench/techdraw/page/redraw": ("Redibuja y actualiza la hoja.", "Redraws and refreshes the sheet.", "Redesenha e atualiza a folha.", "techpage"),
    "workbench/techdraw/page/print": ("Imprime la hoja activa.", "Prints the active sheet.", "Imprime a folha ativa.", "techpage"),
    "workbench/techdraw/page/pdf": ("Exporta la hoja activa a PDF.", "Exports the active sheet to PDF.", "Exporta a folha ativa para PDF.", "techpage"),
    "workbench/techdraw/page/dxf": ("Exporta la hoja activa a DXF.", "Exports the active sheet to DXF.", "Exporta a folha ativa para DXF.", "techpage"),
    "workbench/techdraw/page/svg": ("Exporta la hoja activa a SVG.", "Exports the active sheet to SVG.", "Exporta a folha ativa para SVG.", "techpage"),
    "workbench/techdraw/annotations": ("Anotaciones, globos y cotas axonométricas.", "Annotations, balloons and axonometric dimensions.", "Anotações, balões e cotas axonométricas.", "techpage"),
    "workbench/techdraw/annotations/annotation": ("Agrega una nota de texto a la hoja.", "Adds a text note to the sheet.", "Adiciona uma nota de texto à folha."),
    "workbench/techdraw/annotations/axo_length": ("Cota de longitud en vista axonométrica.", "Length dimension in an axonometric view.", "Cota de comprimento em vista axonométrica.", "techview"),
    "workbench/techdraw/annotations/balloon": ("Agrega un globo (burbuja) con número o texto.", "Adds a balloon with a number or text.", "Adiciona um balão com número ou texto.", "techview"),
    "workbench/techdraw/hatching": ("Rayado y tramado de caras.", "Hatching of faces.", "Hachura de faces.", "techview"),
    "workbench/techdraw/hatching/geometric_hatch": ("Aplica un rayado geométrico a una cara.", "Applies a geometric hatch to a face.", "Aplica uma hachura geométrica a uma face."),
    "workbench/techdraw/addvertices": ("Vértices cosméticos.", "Cosmetic vertices.", "Vértices cosméticos.", "techview"),
    "workbench/techdraw/addvertices/cosmetic": ("Agrega un vértice cosmético (punto de referencia).", "Adds a cosmetic vertex (reference point).", "Adiciona um vértice cosmético (ponto de referência)."),
    "workbench/techdraw/otherviews": ("Otras vistas del documento.", "Other views of the document.", "Outras vistas do documento.", "techpage"),
    "workbench/techdraw/otherviews/active_view": ("Inserta la vista activa del documento en la hoja.", "Inserts the document's active view into the sheet.", "Insere a vista ativa do documento na folha."),
    "workbench/techdraw/features": ("Campos de plantilla, imágenes y símbolos.", "Template fields, images and symbols.", "Campos de modelo, imagens e símbolos.", "techpage"),
    "workbench/techdraw/features/fields": ("Rellena los campos de la plantilla (título, autor…).", "Fills in the template fields (title, author…).", "Preenche os campos do modelo (título, autor…)."),
    "workbench/techdraw/features/image": ("Inserta una imagen en la hoja.", "Inserts an image into the sheet.", "Insere uma imagem na folha."),
    "workbench/techdraw/features/symbol": ("Inserta un símbolo SVG en la hoja.", "Inserts an SVG symbol into the sheet.", "Insere um símbolo SVG na folha."),
}
