"""Descripciones del manual: Explorer, comandos globales, vistas estándar, atributos y selección.

Cada entrada: ruta -> (español, inglés, portugués[, código de requisito]).
La ruta es la de ``arbol.py`` (claves internas del diccionario). Los códigos de
requisito están en ``textos.py``.
"""

G = {  # requisito por defecto de un grupo y de todo lo que cuelga de él
    "explorer": "doc",
    "explorer/file": "none",
    "explorer/proyecto": "none",
    "explorer/windows": "none",
    "explorer/examples": "none",
    "stdview": "view3d",
    "lineattributes": "techpage",
    "selection": "doc",
}

D = {
    # ---------------------------------------------------------------- Explorer
    "explorer": ("Archivos, edición, impresión, ventanas y herramientas generales.",
                 "Files, editing, printing, windows and general tools.",
                 "Arquivos, edição, impressão, janelas e ferramentas gerais."),
    "explorer/file": ("Gestión de documentos con los diálogos nativos de FreeCAD.",
                      "Document management with FreeCAD's native dialogs.",
                      "Gestão de documentos com os diálogos nativos do FreeCAD."),
    "explorer/file/new": ("Crea un documento nuevo en blanco.", "Creates a new blank document.", "Cria um documento novo em branco.", "none"),
    "explorer/file/open": ("Abre el explorador de archivos del sistema para cargar un proyecto.", "Opens the system file browser to load a project.", "Abre o explorador de arquivos do sistema para carregar um projeto.", "none"),
    "explorer/file/save": ("Guarda el documento activo en su ruta actual.", "Saves the active document to its current path.", "Salva o documento ativo no caminho atual.", "docsaved"),
    "explorer/file/saveas": ("Guarda el documento activo con otro nombre o ruta.", "Saves the active document under a new name or path.", "Salva o documento ativo com outro nome ou caminho."),
    "explorer/file/savecopy": ("Guarda una copia sin cambiar el archivo de trabajo.", "Saves a copy without changing the working file.", "Salva uma cópia sem alterar o arquivo de trabalho."),
    "explorer/file/revert": ("Descarta los cambios y restaura la última versión guardada.", "Discards changes and restores the last saved version.", "Descarta as alterações e restaura a última versão salva.", "docsaved"),
    "explorer/file/merge": ("Incorpora el contenido de otro archivo FCStd al documento.", "Merges the contents of another FCStd file into the document.", "Incorpora o conteúdo de outro arquivo FCStd ao documento."),
    "explorer/file/import": ("Importa modelos externos 2D/3D (STEP, IGES, DXF, OBJ…).", "Imports external 2D/3D models (STEP, IGES, DXF, OBJ…).", "Importa modelos externos 2D/3D (STEP, IGES, DXF, OBJ…)."),
    "explorer/file/export": ("Exporta la selección a formatos externos 2D/3D.", "Exports the selection to external 2D/3D formats.", "Exporta a seleção para formatos externos 2D/3D.", "sel"),
    "explorer/file/recent": ("Muestra los últimos documentos abiertos.", "Shows the most recently opened documents.", "Mostra os últimos documentos abertos.", "none"),
    "explorer/file/loadimage": ("Inserta una imagen como plano de referencia en el espacio 3D.", "Inserts an image as a reference plane in 3D space.", "Insere uma imagem como plano de referência no espaço 3D."),

    "explorer/proyecto": ("Abrir, guardar y exportar con ventanas de voz (sin diálogos nativos).",
                          "Open, save and export with voice windows (no native dialogs).",
                          "Abrir, salvar e exportar com janelas de voz (sem diálogos nativos)."),
    "explorer/proyecto/new": ("Crea un proyecto nuevo (equivale a «nuevo» de archivo).", "Creates a new project (same as file «new»).", "Cria um projeto novo (equivale a «novo» de arquivo)."),
    "explorer/proyecto/open": ("Recorre las carpetas por voz (siguiente, anterior, abrir, subir) y abre el archivo elegido.", "Browses folders by voice (next, previous, open, up) and opens the chosen file.", "Percorre as pastas por voz (próximo, anterior, abrir, subir) e abre o arquivo escolhido."),
    "explorer/proyecto/save": ("Guarda el documento; si es nuevo pregunta carpeta y nombre por voz.", "Saves the document; if it is new it asks for folder and name by voice.", "Salva o documento; se for novo pergunta pasta e nome por voz."),
    "explorer/proyecto/export": ("Elige formato (STEP, IGES, STL, OBJ, DXF), carpeta y nombre, y exporta la selección o todo lo visible.", "Chooses format (STEP, IGES, STL, OBJ, DXF), folder and name, and exports the selection or everything visible.", "Escolhe formato (STEP, IGES, STL, OBJ, DXF), pasta e nome, e exporta a seleção ou tudo que está visível."),
    "explorer/proyecto/print3d": ("Elige formato (3MF, STL, OBJ), carpeta y nombre, y exporta las piezas sólidas listas para imprimir en 3D.", "Chooses format (3MF, STL, OBJ), folder and name, and exports the solid parts ready for 3D printing.", "Escolhe formato (3MF, STL, OBJ), pasta e nome, e exporta as peças sólidas prontas para impressão 3D.", "solid"),

    "explorer/edit": ("Deshacer, portapapeles, posición y propiedades.",
                      "Undo, clipboard, placement and properties.",
                      "Desfazer, área de transferência, posição e propriedades."),
    "explorer/edit/undo": ("Revierte la última acción realizada.", "Reverts the last action performed.", "Reverte a última ação realizada.", "history"),
    "explorer/edit/redo": ("Vuelve a aplicar la última acción deshecha.", "Reapplies the last undone action.", "Reaplica a última ação desfeita.", "history"),
    "explorer/edit/cut": ("Copia al portapapeles y elimina el objeto seleccionado.", "Copies to the clipboard and removes the selected object.", "Copia para a área de transferência e remove o objeto selecionado.", "sel"),
    "explorer/edit/copy": ("Copia la selección actual al portapapeles.", "Copies the current selection to the clipboard.", "Copia a seleção atual para a área de transferência.", "sel"),
    "explorer/edit/paste": ("Pega el contenido del portapapeles en el documento activo.", "Pastes the clipboard contents into the active document.", "Cola o conteúdo da área de transferência no documento ativo.", "clip"),
    "explorer/edit/duplicate": ("Crea una copia idéntica e independiente de la selección.", "Creates an identical, independent copy of the selection.", "Cria uma cópia idêntica e independente da seleção.", "sel"),
    "explorer/edit/selectall": ("Selecciona todos los objetos del documento.", "Selects every object in the document.", "Seleciona todos os objetos do documento.", "docobj"),
    "explorer/edit/delete": ("Elimina los objetos seleccionados del documento.", "Deletes the selected objects from the document.", "Exclui os objetos selecionados do documento.", "sel"),
    "explorer/edit/placement": ("Abre el diálogo de posición y rotación numéricas.", "Opens the numeric position and rotation dialog.", "Abre o diálogo de posição e rotação numéricas.", "sel3d"),
    "explorer/edit/transform": ("Activa los manipuladores 3D para mover y rotar el objeto.", "Enables the 3D manipulators to move and rotate the object.", "Ativa os manipuladores 3D para mover e rotacionar o objeto.", "sel3d"),
    "explorer/edit/align": ("Abre la herramienta para alinear dos o más objetos.", "Opens the tool to align two or more objects.", "Abre a ferramenta para alinhar dois ou mais objetos.", "sel2"),
    "explorer/edit/preferences": ("Abre el panel general de preferencias de FreeCAD.", "Opens FreeCAD's general preferences panel.", "Abre o painel geral de preferências do FreeCAD.", "none"),
    "explorer/edit/properties": ("Enfoca el panel de propiedades (Datos/Vista) del objeto.", "Focuses the object's properties panel (Data/View).", "Foca o painel de propriedades (Dados/Vista) do objeto.", "sel"),
    "explorer/edit/sendtopython": ("Envía la referencia del objeto a la consola de Python.", "Sends the object reference to the Python console.", "Envia a referência do objeto para o console Python.", "sel"),
    "explorer/edit/editmode": ("Entra al modo de edición interactivo del objeto.", "Enters the object's interactive edit mode.", "Entra no modo de edição interativo do objeto.", "editable"),

    "explorer/print": ("Impresión física y exportación a PDF de la vista o la hoja.",
                       "Physical printing and PDF export of the view or sheet.",
                       "Impressão física e exportação para PDF da vista ou da folha."),
    "explorer/print/print": ("Abre la ventana de impresión de la vista o lámina actual.", "Opens the print dialog for the current view or sheet.", "Abre a janela de impressão da vista ou folha atual.", "view2d"),
    "explorer/print/pdf": ("Exporta la vista o lámina actual a un PDF vectorial.", "Exports the current view or sheet to a vector PDF.", "Exporta a vista ou folha atual para um PDF vetorial.", "view2d"),

    "explorer/windows": ("Cierra pestañas, documentos o la aplicación.", "Closes tabs, documents or the application.", "Fecha abas, documentos ou o aplicativo."),
    "explorer/windows/close": ("Cierra la pestaña o documento activo.", "Closes the active tab or document.", "Fecha a aba ou o documento ativo.", "doc"),
    "explorer/windows/closeall": ("Cierra todas las pestañas de proyectos abiertas.", "Closes all open project tabs.", "Fecha todas as abas de projetos abertas.", "doc"),
    "explorer/windows/quit": ("Cierra FreeCAD por completo, previa confirmación de guardado.", "Closes FreeCAD completely, asking to save first.", "Fecha o FreeCAD por completo, após confirmação de salvamento.", "none"),

    "explorer/expressions": ("Copia y pega referencias de expresiones y fórmulas.",
                             "Copies and pastes expression and formula references.",
                             "Copia e cola referências de expressões e fórmulas."),
    "explorer/expressions/copyactdoc": ("Copia la referencia del documento activo para usarla en fórmulas.", "Copies the active document reference for use in formulas.", "Copia a referência do documento ativo para uso em fórmulas.", "docsaved"),
    "explorer/expressions/copyalldoc": ("Copia todas las referencias de expresiones del árbol.", "Copies every expression reference in the tree.", "Copia todas as referências de expressões da árvore.", "doc"),
    "explorer/expressions/copyselected": ("Copia la ruta de fórmula del parámetro seleccionado.", "Copies the formula path of the selected parameter.", "Copia o caminho de fórmula do parâmetro selecionado.", "sel"),
    "explorer/expressions/pasteexpr": ("Pega y vincula la expresión copiada en la propiedad seleccionada.", "Pastes and binds the copied expression into the selected property.", "Cola e vincula a expressão copiada na propriedade selecionada.", "propedit"),

    "explorer/tools": ("Medir, personalizar y utilidades avanzadas.",
                       "Measure, customize and advanced utilities.",
                       "Medir, personalizar e utilitários avançados."),
    "explorer/tools/measure": ("Activa la regla interactiva para medir distancias y ángulos.", "Activates the interactive ruler to measure distances and angles.", "Ativa a régua interativa para medir distâncias e ângulos.", "view3d"),
    "explorer/tools/clarifyselection": ("Despliega un menú que clasifica lo seleccionado por tipo de geometría.", "Shows a menu that sorts the selection by geometry type.", "Exibe um menu que classifica a seleção por tipo de geometria.", "sel"),
    "explorer/tools/demomode": ("Gira la cámara de forma continua para presentar el modelo.", "Rotates the camera continuously to present the model.", "Gira a câmera continuamente para apresentar o modelo.", "view3d"),
    "explorer/tools/customize": ("Abre el diálogo para personalizar atajos, barras y comandos.", "Opens the dialog to customize shortcuts, toolbars and commands.", "Abre o diálogo para personalizar atalhos, barras e comandos.", "none"),
    "explorer/tools/editparameters": ("Abre el editor avanzado de parámetros de FreeCAD.", "Opens FreeCAD's advanced parameter editor.", "Abre o editor avançado de parâmetros do FreeCAD.", "none"),
    "explorer/tools/projectutil": ("Abre la utilidad que descomprime y repara la estructura de un archivo .FCStd.", "Opens the utility that unpacks and repairs the structure of an .FCStd file.", "Abre o utilitário que descompacta e repara a estrutura de um arquivo .FCStd.", "none"),

    "explorer/structure": ("Contenedores estructurales y enlaces (Links).",
                           "Structural containers and links.",
                           "Contêineres estruturais e vínculos (Links)."),
    "explorer/structure/part": ("Crea un contenedor Part para agrupar cuerpos o sólidos.", "Creates a Part container to group bodies or solids.", "Cria um contêiner Part para agrupar corpos ou sólidos.", "doc"),
    "explorer/structure/newgroup": ("Crea una carpeta de grupo genérica en el árbol.", "Creates a generic group folder in the tree.", "Cria uma pasta de grupo genérica na árvore.", "doc"),
    "explorer/structure/linkactions": ("Creación y gestión de instancias vinculadas.", "Creating and managing linked instances.", "Criação e gestão de instâncias vinculadas."),
    "explorer/structure/linkactions/makelink": ("Genera un vínculo ligero (App::Link) hacia un objeto existente.", "Creates a lightweight link (App::Link) to an existing object.", "Gera um vínculo leve (App::Link) para um objeto existente.", "sel"),
    "explorer/structure/linkactions/relativelink": ("Genera un vínculo a un subelemento relativo.", "Creates a link to a relative sub-element.", "Gera um vínculo para um subelemento relativo.", "sel"),
    "explorer/structure/linkactions/importlink": ("Importa un objeto externo como vínculo.", "Imports an external object as a link.", "Importa um objeto externo como vínculo.", "doc"),
    "explorer/structure/linkactions/importalllinks": ("Importa todos los elementos vinculados al archivo activo.", "Imports every linked element into the active file.", "Importa todos os elementos vinculados ao arquivo ativo.", "extlinks"),
    "explorer/structure/linkactions/replacelink": ("Reemplaza un vínculo por su objeto original.", "Replaces a link with its original object.", "Substitui um vínculo pelo objeto original.", "sel"),
    "explorer/structure/linkactions/linkgroups": ("Agrupa varios vínculos en un contenedor.", "Groups several links in a container.", "Agrupa vários vínculos em um contêiner.", "doc"),

    "explorer/examples": ("Manual de usuario y ejemplos guiados paso a paso.",
                          "User manual and step-by-step guided examples.",
                          "Manual do usuário e exemplos guiados passo a passo."),
    "explorer/examples/manual": ("Abre el manual de usuario (PDF) en el idioma de DAV.", "Opens the user manual (PDF) in the DAV language.", "Abre o manual do usuário (PDF) no idioma do DAV.", "none"),
    "explorer/examples/demos": ("Abre el selector de ejemplos guiados (croquis, borrador, dado, arandela, bulón-tuerca, tijera…).", "Opens the guided example picker (sketch, draft, die, washer, bolt-nut, scissors…).", "Abre o seletor de exemplos guiados (croqui, rascunho, dado, arruela, parafuso-porca, tesoura…).", "none"),

    "explorer/refresh": ("Recalcula y actualiza el árbol y la vista 3D del documento.", "Recomputes and refreshes the tree and the 3D view.", "Recalcula e atualiza a árvore e a vista 3D do documento.", "doc"),
    "explorer/screenshot": ("Abre el diálogo para guardar una imagen de la vista 3D.", "Opens the dialog to save an image of the 3D view.", "Abre o diálogo para salvar uma imagem da vista 3D.", "view3d"),
    "explorer/textdoc": ("Crea una nota o documento de texto dentro del árbol.", "Creates a note or text document inside the tree.", "Cria uma nota ou documento de texto dentro da árvore.", "doc"),
    "explorer/unlink": ("Rompe el vínculo del objeto con su fuente original.", "Breaks the object's link to its original source.", "Rompe o vínculo do objeto com a fonte original.", "linksel"),
    "explorer/freeze": ("Inmoviliza el objeto para evitar su recálculo automático.", "Freezes the object to prevent automatic recomputation.", "Congela o objeto para evitar o recálculo automático.", "sel"),
    "explorer/allinstances": ("Selecciona todas las instancias compartidas del objeto.", "Selects every shared instance of the object.", "Seleciona todas as instâncias compartilhadas do objeto.", "multiinst"),
    "explorer/variableset": ("Crea un VarSet para guardar variables y expresiones globales.", "Creates a VarSet to store global variables and expressions.", "Cria um VarSet para guardar variáveis e expressões globais.", "doc"),

    # ----------------------------------------------------- Comandos globales
    "global/undo": ("Deshace el último cambio del documento.", "Undoes the last change in the document.", "Desfaz a última alteração do documento.", "history"),
    "global/redo": ("Rehace el último cambio deshecho.", "Redoes the last undone change.", "Refaz a última alteração desfeita.", "history"),
    "global/deleteLast": ("Borra el último objeto creado, con confirmación por voz.", "Deletes the last object created, with voice confirmation.", "Apaga o último objeto criado, com confirmação por voz.", "doc"),
    "global/deleteObject": ("Borra un objeto elegido por voz, con confirmación.", "Deletes an object chosen by voice, with confirmation.", "Apaga um objeto escolhido por voz, com confirmação.", "doc"),
    "global/deleteBroken": ("Elimina los objetos con error o rotos, con confirmación.", "Removes broken or errored objects, with confirmation.", "Remove os objetos com erro ou quebrados, com confirmação.", "doc"),
    "global/CreateDimension": ("Crea una cota entre los elementos seleccionados.", "Creates a dimension between the selected elements.", "Cria uma cota entre os elementos selecionados.", "sel"),
    "global/MoveView": ("Centra la cámara en el punto indicado y la desplaza.", "Centers the camera on the given point and pans it.", "Centraliza a câmera no ponto indicado e a desloca.", "view3d"),
    "global/ayuda": ("Muestra la ayuda del contexto actual.", "Shows help for the current context.", "Mostra a ajuda do contexto atual.", "none"),
    "preferences": ("Abre la ventana de preferencias de DAV (modelo de voz, idioma).", "Opens the DAV preferences window (voice model, language).", "Abre a janela de preferências do DAV (modelo de voz, idioma).", "none"),
    "hide_dav_panel": ("Minimiza el panel de DAV.", "Minimizes the DAV panel.", "Minimiza o painel do DAV.", "none"),
    "show_dav_panel": ("Vuelve a mostrar el panel de DAV.", "Shows the DAV panel again.", "Mostra novamente o painel do DAV.", "none"),

    # --------------------------------------------------------------- StdView
    "stdview": ("Vistas, cámara, apariencia, paneles y árbol.", "Views, camera, appearance, panels and tree.", "Vistas, câmera, aparência, painéis e árvore."),
    "stdview/appearance": ("Colores, texturas y apariencia de los objetos.", "Colors, textures and appearance of objects.", "Cores, texturas e aparência dos objetos."),
    "stdview/appearance/appearance": ("Abre el panel de apariencia del objeto seleccionado.", "Opens the appearance panel of the selected object.", "Abre o painel de aparência do objeto selecionado.", "sel"),
    "stdview/appearance/facecolor": ("Asigna colores distintos a cada cara de la pieza.", "Assigns a different color to each face of the part.", "Atribui uma cor diferente a cada face da peça.", "sel"),
    "stdview/appearance/randomcolor": ("Asigna un color aleatorio al objeto.", "Assigns a random color to the object.", "Atribui uma cor aleatória ao objeto.", "sel"),
    "stdview/appearance/texturemapping": ("Aplica o edita el mapeo de texturas del objeto.", "Applies or edits the object's texture mapping.", "Aplica ou edita o mapeamento de texturas do objeto.", "sel"),
    "stdview/camera": ("Tipo de proyección de la cámara.", "Camera projection type.", "Tipo de projeção da câmera."),
    "stdview/camera/orthographic": ("Cambia a vista ortográfica (sin perspectiva).", "Switches to orthographic view (no perspective).", "Muda para vista ortográfica (sem perspectiva)."),
    "stdview/camera/perspective": ("Cambia a vista en perspectiva.", "Switches to perspective view.", "Muda para vista em perspectiva."),
    "stdview/clipping": ("Plano de recorte de la vista 3D.", "Clipping plane of the 3D view.", "Plano de corte da vista 3D."),
    "stdview/clipping/clipping": ("Activa el plano de recorte para ver el interior de las piezas.", "Enables the clipping plane to see inside parts.", "Ativa o plano de corte para ver o interior das peças."),
    "stdview/drawstyles": ("Estilo de dibujo de la geometría.", "Drawing style of the geometry.", "Estilo de desenho da geometria."),
    "stdview/drawstyles/styleasis": ("Muestra el modelo tal como está definido.", "Shows the model as defined.", "Mostra o modelo como está definido."),
    "stdview/drawstyles/points": ("Muestra solo los puntos.", "Shows points only.", "Mostra apenas os pontos."),
    "stdview/drawstyles/wireframe": ("Muestra solo las aristas (alambre).", "Shows edges only (wireframe).", "Mostra apenas as arestas (arame)."),
    "stdview/drawstyles/hiddenline": ("Muestra aristas ocultando las que quedan detrás.", "Shows edges hiding those behind surfaces.", "Mostra arestas ocultando as que ficam atrás."),
    "stdview/drawstyles/noshading": ("Muestra caras sin sombreado.", "Shows faces without shading.", "Mostra faces sem sombreamento."),
    "stdview/drawstyles/shaded": ("Muestra el sólido sombreado.", "Shows the shaded solid.", "Mostra o sólido sombreado."),
    "stdview/drawstyles/flatlines": ("Muestra caras planas con sus aristas.", "Shows flat faces with their edges.", "Mostra faces planas com suas arestas."),
    "stdview/material": ("Materiales de la biblioteca.", "Library materials.", "Materiais da biblioteca."),
    "stdview/material/material": ("Asigna un material de la biblioteca al objeto.", "Assigns a library material to the object.", "Atribui um material da biblioteca ao objeto.", "sel"),
    "stdview/overlay": ("Paneles superpuestos sobre la vista 3D.", "Panels overlaid on the 3D view.", "Painéis sobrepostos à vista 3D."),
    "stdview/overlay/bottom": ("Superpone el panel inferior.", "Overlays the bottom panel.", "Sobrepõe o painel inferior."),
    "stdview/overlay/float": ("Convierte el panel en flotante.", "Makes the panel floating.", "Torna o painel flutuante."),
    "stdview/overlay/left": ("Superpone el panel izquierdo.", "Overlays the left panel.", "Sobrepõe o painel esquerdo."),
    "stdview/overlay/right": ("Superpone el panel derecho.", "Overlays the right panel.", "Sobrepõe o painel direito."),
    "stdview/overlay/axis": ("Muestra u oculta la cruz de ejes.", "Shows or hides the axis cross.", "Mostra ou oculta a cruz de eixos."),
    "stdview/overlay/navigation": ("Alterna el panel de navegación.", "Toggles the navigation panel.", "Alterna o painel de navegação."),
    "stdview/overlay/toggle": ("Alterna la superposición de paneles.", "Toggles the panel overlay.", "Alterna a sobreposição de painéis."),
    "stdview/panels": ("Abrir, acoplar y cerrar paneles de FreeCAD.", "Open, dock and close FreeCAD panels.", "Abrir, acoplar e fechar painéis do FreeCAD."),
    "stdview/panels/panel": ("Muestra u oculta el panel principal (DAV / vista combinada).", "Shows or hides the main panel (DAV / combo view).", "Mostra ou oculta o painel principal (DAV / vista combinada)."),
    "stdview/panels/dock": ("Acopla la vista actual a la ventana principal.", "Docks the current view into the main window.", "Acopla a vista atual à janela principal."),
    "stdview/panels/fullscreen": ("Alterna la pantalla completa.", "Toggles full screen.", "Alterna a tela cheia."),
    "stdview/panels/undock": ("Desacopla la vista actual en una ventana aparte.", "Undocks the current view into its own window.", "Desacopla a vista atual em uma janela separada."),
    "stdview/panels/dagview": ("Abre la vista DAG (grafo de dependencias).", "Opens the DAG view (dependency graph).", "Abre a vista DAG (grafo de dependências)."),
    "stdview/panels/comboview": ("Muestra u oculta el panel combinado (árbol y tareas).", "Shows or hides the combo panel (tree and tasks).", "Mostra ou oculta o painel combinado (árvore e tarefas)."),
    "stdview/panels/selectionview": ("Abre el panel de vista de selección.", "Opens the selection view panel.", "Abre o painel de vista de seleção."),
    "stdview/panels/tasks": ("Abre el panel de tareas.", "Opens the tasks panel.", "Abre o painel de tarefas."),
    "stdview/panels/properties": ("Abre el panel de propiedades.", "Opens the properties panel.", "Abre o painel de propriedades."),
    "stdview/panels/console": ("Activa la consola de Python.", "Activates the Python console.", "Ativa o console Python."),
    "stdview/panels/report": ("Abre la vista de reporte de mensajes.", "Opens the report message view.", "Abre a vista de relatório de mensagens."),
    "stdview/panels/treeview": ("Muestra u oculta el árbol del modelo.", "Shows or hides the model tree.", "Mostra ou oculta a árvore do modelo."),
    "stdview/panels/statusbar": ("Muestra u oculta la barra de estado.", "Shows or hides the status bar.", "Mostra ou oculta a barra de estado."),
    "stdview/savedviews": ("Vistas guardadas de la cámara.", "Saved camera views.", "Vistas salvas da câmera."),
    "stdview/savedviews/clear": ("Borra las vistas congeladas.", "Clears the frozen views.", "Apaga as vistas congeladas."),
    "stdview/savedviews/freeze": ("Congela la vista actual de la cámara.", "Freezes the current camera view.", "Congela a vista atual da câmera."),
    "stdview/savedviews/restore": ("Restaura la vista congelada elegida.", "Restores the chosen frozen view.", "Restaura a vista congelada escolhida."),
    "stdview/savedviews/recall": ("Recupera la vista de trabajo almacenada.", "Recalls the stored working view.", "Recupera a vista de trabalho armazenada."),
    "stdview/savedviews/load": ("Carga vistas congeladas desde un archivo.", "Loads frozen views from a file.", "Carrega vistas congeladas de um arquivo."),
    "stdview/savedviews/save": ("Guarda las vistas congeladas en un archivo.", "Saves the frozen views to a file.", "Salva as vistas congeladas em um arquivo."),
    "stdview/savedviews/store": ("Almacena la vista actual como vista de trabajo.", "Stores the current view as the working view.", "Armazena a vista atual como vista de trabalho."),
    "stdview/standardviews": ("Vistas estándar, zoom y encuadre. Se pueden decir desde cualquier contexto.", "Standard views, zoom and framing. They can be said from any context.", "Vistas padrão, zoom e enquadramento. Podem ser ditas de qualquer contexto."),
    "stdview/standardviews/bottom": ("Vista inferior.", "Bottom view.", "Vista inferior."),
    "stdview/standardviews/boxzoom": ("Zoom a un rectángulo elegido.", "Zooms to a chosen rectangle.", "Zoom em um retângulo escolhido."),
    "stdview/standardviews/newview": ("Abre una nueva ventana de vista 3D.", "Opens a new 3D view window.", "Abre uma nova janela de vista 3D."),
    "stdview/standardviews/dimetric": ("Vista dimétrica.", "Dimetric view.", "Vista dimétrica."),
    "stdview/standardviews/fitall": ("Encuadra todo el modelo en la vista.", "Fits the whole model in the view.", "Enquadra todo o modelo na vista."),
    "stdview/standardviews/fitselection": ("Encuadra la selección en la vista.", "Fits the selection in the view.", "Enquadra a seleção na vista.", "sel"),
    "stdview/standardviews/front": ("Vista frontal.", "Front view.", "Vista frontal."),
    "stdview/standardviews/fullscreen": ("Alterna la vista a pantalla completa.", "Toggles the view to full screen.", "Alterna a vista para tela cheia."),
    "stdview/standardviews/home": ("Vuelve a la vista inicial.", "Returns to the home view.", "Volta para a vista inicial."),
    "stdview/standardviews/isometric": ("Vista isométrica.", "Isometric view.", "Vista isométrica."),
    "stdview/standardviews/left": ("Vista izquierda.", "Left view.", "Vista esquerda."),
    "stdview/standardviews/rear": ("Vista trasera.", "Rear view.", "Vista traseira."),
    "stdview/standardviews/right": ("Vista derecha.", "Right view.", "Vista direita."),
    "stdview/standardviews/top": ("Vista superior.", "Top view.", "Vista superior."),
    "stdview/standardviews/trimetric": ("Vista trimétrica.", "Trimetric view.", "Vista trimétrica."),
    "stdview/standardviews/zoomin": ("Acerca la vista (zoom).", "Zooms in.", "Aproxima a vista (zoom)."),
    "stdview/standardviews/zoomout": ("Aleja la vista (zoom).", "Zooms out.", "Afasta a vista (zoom)."),
    "stdview/stereo": ("Modos de visualización estereoscópica.", "Stereoscopic viewing modes.", "Modos de visualização estereoscópica."),
    "stdview/stereo/camerapos": ("Muestra en la consola la posición de la cámara.", "Prints the camera position to the console.", "Mostra no console a posição da câmera."),
    "stdview/stereo/stereocolumns": ("Estéreo con columnas entrelazadas.", "Stereo with interlaced columns.", "Estéreo com colunas entrelaçadas."),
    "stdview/stereo/stereorows": ("Estéreo con filas entrelazadas.", "Stereo with interlaced rows.", "Estéreo com linhas entrelaçadas."),
    "stdview/stereo/stereooff": ("Desactiva el modo estéreo.", "Turns stereo mode off.", "Desativa o modo estéreo."),
    "stdview/stereo/stereoquad": ("Estéreo con búfer cuádruple.", "Quad-buffer stereo.", "Estéreo com buffer quádruplo."),
    "stdview/stereo/stereoanaglyph": ("Estéreo anaglifo rojo-verde.", "Red-green anaglyph stereo.", "Estéreo anáglifo vermelho-verde."),
    "stdview/toolbars": ("Mostrar u ocultar barras de herramientas.", "Show or hide toolbars.", "Mostrar ou ocultar barras de ferramentas."),
    "stdview/toolbars/clipboard": ("Alterna la barra del portapapeles.", "Toggles the clipboard toolbar.", "Alterna a barra da área de transferência."),
    "stdview/toolbars/edit": ("Alterna la barra de edición.", "Toggles the edit toolbar.", "Alterna a barra de edição."),
    "stdview/toolbars/file": ("Alterna la barra de archivo.", "Toggles the file toolbar.", "Alterna a barra de arquivo."),
    "stdview/toolbars/toolbarshelp": ("Alterna la barra de ayuda.", "Toggles the help toolbar.", "Alterna a barra de ajuda."),
    "stdview/toolbars/views": ("Alterna la barra de vistas.", "Toggles the views toolbar.", "Alterna a barra de vistas."),
    "stdview/toolbars/lock": ("Bloquea o desbloquea las barras de herramientas.", "Locks or unlocks the toolbars.", "Bloqueia ou desbloqueia as barras de ferramentas."),
    "stdview/toolbars/macro": ("Alterna la barra de macros.", "Toggles the macro toolbar.", "Alterna a barra de macros."),
    "stdview/toolbars/structure": ("Alterna la barra de estructura.", "Toggles the structure toolbar.", "Alterna a barra de estrutura."),
    "stdview/toolbars/view": ("Alterna la barra de vista.", "Toggles the view toolbar.", "Alterna a barra de vista."),
    "stdview/toolbars/workbench": ("Alterna la barra de bancos de trabajo.", "Toggles the workbench toolbar.", "Alterna a barra de bancadas."),
    "stdview/tree": ("Comportamiento del árbol del modelo.", "Behavior of the model tree.", "Comportamento da árvore do modelo."),
    "stdview/tree/collapse": ("Contrae todos los elementos del documento activo en el árbol.", "Collapses every item of the active document in the tree.", "Recolhe todos os itens do documento ativo na árvore."),
    "stdview/tree/preselection": ("Preselecciona en la vista 3D el objeto sobre el que se pasa en el árbol.", "Preselects in the 3D view the object hovered in the tree.", "Pré-seleciona na vista 3D o objeto sobre o qual se passa na árvore."),
    "stdview/tree/recordselection": ("Registra la selección del árbol para poder ir atrás y adelante.", "Records the tree selection so you can go back and forward.", "Registra a seleção da árvore para poder ir e voltar."),
    "stdview/tree/singleexpand": ("Muestra solo el documento activo en el árbol y expande sus elementos.", "Shows only the active document in the tree and expands its items.", "Mostra apenas o documento ativo na árvore e expande seus itens."),
    "stdview/tree/syncplacement": ("Ajusta la posición automáticamente al arrastrar objetos entre sistemas de coordenadas.", "Adjusts placement automatically when dragging objects across coordinate systems.", "Ajusta a posição automaticamente ao arrastar objetos entre sistemas de coordenadas."),
    "stdview/tree/syncselection": ("Expande en el árbol el objeto seleccionado en la vista 3D.", "Expands in the tree the object selected in the 3D view.", "Expande na árvore o objeto selecionado na vista 3D."),
    "stdview/tree/syncview": ("Cambia a la vista 3D que contiene el objeto seleccionado.", "Switches to the 3D view that contains the selected object.", "Muda para a vista 3D que contém o objeto selecionado."),
    "stdview/visibility": ("Mostrar, ocultar y seleccionar por visibilidad.", "Show, hide and select by visibility.", "Mostrar, ocultar e selecionar por visibilidade."),
    "stdview/visibility/hideobjects": ("Oculta todos los objetos.", "Hides all objects.", "Oculta todos os objetos.", "docobj"),
    "stdview/visibility/hide": ("Oculta los objetos seleccionados.", "Hides the selected objects.", "Oculta os objetos selecionados.", "sel"),
    "stdview/visibility/alllinks": ("Selecciona todos los vínculos hacia el objeto seleccionado.", "Selects every link to the selected object.", "Seleciona todos os vínculos para o objeto selecionado.", "sel"),
    "stdview/visibility/linked": ("Selecciona el objeto vinculado.", "Selects the linked object.", "Seleciona o objeto vinculado.", "linksel"),
    "stdview/visibility/linkedfinal": ("Selecciona el objeto final de una cadena de vínculos.", "Selects the final object of a link chain.", "Seleciona o objeto final de uma cadeia de vínculos.", "linksel"),
    "stdview/visibility/selback": ("Vuelve a la selección anterior.", "Goes back to the previous selection.", "Volta para a seleção anterior."),
    "stdview/visibility/boundingbox": ("Muestra la caja delimitadora de la selección.", "Shows the bounding box of the selection.", "Mostra a caixa delimitadora da seleção.", "sel"),
    "stdview/visibility/selforward": ("Avanza a la selección siguiente.", "Goes forward to the next selection.", "Avança para a próxima seleção."),
    "stdview/visibility/selectvisible": ("Selecciona los objetos visibles.", "Selects the visible objects.", "Seleciona os objetos visíveis.", "docobj"),
    "stdview/visibility/showobjects": ("Muestra todos los objetos.", "Shows all objects.", "Mostra todos os objetos.", "docobj"),
    "stdview/visibility/show": ("Muestra los objetos seleccionados.", "Shows the selected objects.", "Mostra os objetos selecionados.", "sel"),
    "stdview/visibility/toggleall": ("Invierte la visibilidad de todos los objetos.", "Inverts the visibility of every object.", "Inverte a visibilidade de todos os objetos.", "docobj"),
    "stdview/visibility/selectability": ("Alterna si los objetos seleccionados se pueden seleccionar con el mouse.", "Toggles whether the selected objects can be picked with the mouse.", "Alterna se os objetos selecionados podem ser escolhidos com o mouse.", "sel"),
    "stdview/visibility/transparency": ("Alterna la transparencia de la selección.", "Toggles the selection's transparency.", "Alterna a transparência da seleção.", "sel"),
    "stdview/visibility/toggle": ("Alterna la visibilidad de la selección.", "Toggles the selection's visibility.", "Alterna a visibilidade da seleção.", "sel"),
    "stdview/visibility/aligntoselection": ("Alinea la vista con la selección.", "Aligns the view with the selection.", "Alinha a vista com a seleção.", "sel"),

    # -------------------------------------------------------- LineAttributes
    "lineattributes": ("Estilo, grosor y color de línea de las vistas de TechDraw.", "Line style, width and color for TechDraw views.", "Estilo, espessura e cor de linha das vistas do TechDraw."),
    "lineattributes/attributes": ("Elegir y aplicar atributos de línea en dos pasos.", "Pick and apply line attributes in two steps.", "Escolher e aplicar atributos de linha em dois passos."),
    "lineattributes/attributes/select": ("Paso 1: elige los atributos (estilo, grosor, color) a aplicar.", "Step 1: chooses the attributes (style, width, color) to apply.", "Passo 1: escolhe os atributos (estilo, espessura, cor) a aplicar.", "techpage"),
    "lineattributes/attributes/change": ("Paso 2: aplica los atributos elegidos a las líneas seleccionadas.", "Step 2: applies the chosen attributes to the selected lines.", "Passo 2: aplica os atributos escolhidos às linhas selecionadas.", "techlines"),

    # ------------------------------------------------------------- Selection
    "selection": ("Recorre y selecciona los objetos del documento sin usar el mouse.", "Steps through and selects document objects without the mouse.", "Percorre e seleciona os objetos do documento sem usar o mouse."),
    "selection/next": ("Avanza al siguiente objeto de la lista y lo resalta.", "Moves to the next object in the list and highlights it.", "Avança para o próximo objeto da lista e o destaca.", "docobj"),
    "selection/previous": ("Retrocede al objeto anterior de la lista y lo resalta.", "Moves back to the previous object in the list and highlights it.", "Volta ao objeto anterior da lista e o destaca.", "docobj"),
    "selection/selectall": ("Selecciona todos los objetos del documento.", "Selects every object in the document.", "Seleciona todos os objetos do documento.", "docobj"),
    "selection/deselectall": ("Desmarca la selección, dejando la escena sin objetos seleccionados.", "Clears the selection, leaving nothing selected.", "Desmarca a seleção, deixando a cena sem objetos selecionados.", "none"),
    "selection/current": ("Dice el nombre del objeto actual.", "Says the name of the current object.", "Diz o nome do objeto atual.", "docobj"),
    "selection/count": ("Informa cuántos objetos hay en el documento.", "Reports how many objects the document has.", "Informa quantos objetos o documento tem.", "doc"),
    "selection/delete": ("Borra el objeto seleccionado (primero siguiente/anterior, luego borrar).", "Deletes the selected object (first next/previous, then delete).", "Apaga o objeto selecionado (primeiro próximo/anterior, depois apagar).", "sel"),
    "selection/spell": ("Deletrea el nombre de un objeto y selecciona el más parecido.", "Spell an object's name and selects the closest match.", "Soletra o nome de um objeto e seleciona o mais parecido.", "docobj"),
    "selection/color": ("Pinta los objetos seleccionados con un color elegido por voz.", "Paints the selected objects with a color picked by voice.", "Pinta os objetos selecionados com uma cor escolhida por voz.", "sel"),
    "selection/material": ("Asigna un material de la biblioteca a lo seleccionado, elegido por voz.", "Gives the selection a library material picked by voice.", "Atribui à seleção um material da biblioteca escolhido por voz.", "sel"),
}
