"""Textos fijos del manual de usuario en español, inglés y portugués.

Los comandos y sus descripciones no están acá: salen de ``arbol.py`` (frases e íconos
reales de los diccionarios) y de los ``desc_*.py`` (qué hace cada uno).
"""

IDIOMAS = ("es", "en", "pt")
ARCHIVO = {"es": "Manual_Usuario.pdf", "en": "User_Manual.pdf", "pt": "Manual_do_Usuario.pdf"}

# Requisitos reutilizables: código -> (es, en, pt)
REQ = {
    "none": ("Ninguno.", "None.", "Nenhum."),
    "doc": ("Documento activo.", "Active document.", "Documento ativo."),
    "docsaved": ("Documento activo ya guardado.", "Active document already saved.", "Documento ativo já salvo."),
    "docobj": ("Documento con objetos.", "Document with objects.", "Documento com objetos."),
    "docfont": ("Documento activo y un archivo de tipografía.", "Active document and a font file.", "Documento ativo e um arquivo de fonte."),
    "history": ("Historial de acciones disponible.", "Action history available.", "Histórico de ações disponível."),
    "clip": ("Algo copiado en el portapapeles.", "Something copied to the clipboard.", "Algo copiado na área de transferência."),
    "sel": ("Objeto seleccionado.", "Selected object.", "Objeto selecionado."),
    "sel2": ("Dos o más objetos seleccionados.", "Two or more selected objects.", "Dois ou mais objetos selecionados."),
    "sel3d": ("Objeto 3D seleccionado.", "Selected 3D object.", "Objeto 3D selecionado."),
    "solid": ("Pieza o sólido seleccionado.", "Selected part or solid.", "Peça ou sólido selecionado."),
    "editable": ("Objeto editable (croquis, malla, etc.).", "Editable object (sketch, mesh, etc.).", "Objeto editável (croqui, malha etc.)."),
    "view2d": ("Vista 2D/3D o plano de TechDraw activo.", "Active 2D/3D view or TechDraw sheet.", "Vista 2D/3D ou folha do TechDraw ativa."),
    "view3d": ("Vista 3D activa.", "Active 3D view.", "Vista 3D ativa."),
    "propedit": ("Propiedad abierta en edición.", "Property open for editing.", "Propriedade aberta para edição."),
    "extlinks": ("Vínculos externos en el proyecto.", "External links in the project.", "Vínculos externos no projeto."),
    "linksel": ("Vínculo (Link) seleccionado.", "Selected link.", "Vínculo (Link) selecionado."),
    "multiinst": ("Objeto con varias instancias en la escena.", "Object with several instances in the scene.", "Objeto com várias instâncias na cena."),
    # Assembly / PartDesign
    "asm": ("Ensamblaje activo.", "Active assembly.", "Montagem ativa."),
    "asm2": ("Ensamblaje con dos piezas o caras/aristas elegidas.", "Assembly with two parts or chosen faces/edges.", "Montagem com duas peças ou faces/arestas escolhidas."),
    "body": ("Cuerpo (Body) activo.", "Active Body.", "Corpo (Body) ativo."),
    "body2": ("Dos cuerpos en el documento.", "Two bodies in the document.", "Dois corpos no documento."),
    "bodysolid": ("Cuerpo activo con un sólido.", "Active Body with a solid.", "Corpo ativo com um sólido."),
    "bodysk": ("Cuerpo activo y un croquis cerrado.", "Active Body and a closed sketch.", "Corpo ativo e um croqui fechado."),
    "bodysk2": ("Cuerpo activo y dos o más croquis.", "Active Body and two or more sketches.", "Corpo ativo e dois ou mais croquis."),
    "bodysksolid": ("Sólido en el cuerpo y un croquis cerrado.", "Solid in the Body and a closed sketch.", "Sólido no corpo e um croqui fechado."),
    "bodysk2solid": ("Sólido en el cuerpo y dos o más croquis.", "Solid in the Body and two or more sketches.", "Sólido no corpo e dois ou mais croquis."),
    "seledge": ("Una o más aristas seleccionadas.", "One or more selected edges.", "Uma ou mais arestas selecionadas."),
    "selface": ("Una o más caras seleccionadas.", "One or more selected faces.", "Uma ou mais faces selecionadas."),
    "selfeat": ("Operación (feature) seleccionada.", "Selected feature.", "Operação (feature) selecionada."),
    # Sketcher
    "sketch": ("Croquis abierto (en edición).", "Open sketch (in edit mode).", "Croqui aberto (em edição)."),
    "sksel": ("Croquis seleccionado.", "Selected sketch.", "Croqui selecionado."),
    "sk2sel": ("Dos o más croquis seleccionados.", "Two or more selected sketches.", "Dois ou mais croquis selecionados."),
    "skpt": ("Un punto del croquis.", "A sketch point.", "Um ponto do croqui."),
    "sk2pts": ("Dos puntos del croquis.", "Two sketch points.", "Dois pontos do croqui."),
    "skptline": ("Un punto y una línea o curva.", "A point and a line or curve.", "Um ponto e uma linha ou curva."),
    "skline": ("Una o más líneas del croquis.", "One or more sketch lines.", "Uma ou mais linhas do croqui."),
    "sk2lines": ("Dos o más líneas del croquis.", "Two or more sketch lines.", "Duas ou mais linhas do croqui."),
    "sk2curves": ("Dos curvas o una curva y una línea.", "Two curves or a curve and a line.", "Duas curvas ou uma curva e uma linha."),
    "skgeom": ("Geometría seleccionada en el croquis.", "Geometry selected in the sketch.", "Geometria selecionada no croqui."),
    "skconstraint": ("Restricción seleccionada.", "Selected constraint.", "Restrição selecionada."),
    "skext": ("Croquis abierto y geometría externa visible.", "Open sketch and visible external geometry.", "Croqui aberto e geometria externa visível."),
    "bspline": ("Curva B-Spline seleccionada en el croquis.", "B-Spline curve selected in the sketch.", "Curva B-Spline selecionada no croqui."),
    # Draft / Part
    "plane": ("Plano de trabajo activo.", "Active working plane.", "Plano de trabalho ativo."),
    "selpath": ("Objeto y trayectoria seleccionados.", "Object and path selected.", "Objeto e trajetória selecionados."),
    "selpoint": ("Objeto y puntos seleccionados.", "Object and points selected.", "Objeto e pontos selecionados."),
    "selvertex": ("Vértice u objeto con vértices seleccionado.", "Selected vertex or object with vertices.", "Vértice ou objeto com vértices selecionado."),
    "seledge": ("Una o más aristas seleccionadas.", "One or more selected edges.", "Uma ou mais arestas selecionadas."),
    "selpart": ("Objeto Part seleccionado.", "Selected Part object.", "Objeto Part selecionado."),
    "selprofile": ("Croquis o contorno seleccionado.", "Selected sketch or outline.", "Croqui ou contorno selecionado."),
    "selprofiles": ("Dos o más perfiles seleccionados.", "Two or more selected profiles.", "Dois ou mais perfis selecionados."),
    "selwire": ("Contorno o cara 2D seleccionados.", "Selected 2D wire or face.", "Contorno ou face 2D selecionados."),
    "selsurf": ("Superficie de apoyo y al menos una forma.", "Support surface and at least one shape.", "Superfície de apoio e pelo menos uma forma."),
    "sel2edges": ("Exactamente dos aristas o curvas.", "Exactly two edges or curves.", "Exatamente duas arestas ou curvas."),
    "sel2part": ("Exactamente dos objetos Part.", "Exactly two Part objects.", "Exatamente dois objetos Part."),
    "selsweep": ("Perfil y trayectoria guía seleccionados.", "Profile and guide path selected.", "Perfil e trajetória guia selecionados."),
    "dimsel": ("Cota de Draft seleccionada.", "Selected Draft dimension.", "Cota do Draft selecionada."),
    # TechDraw
    "techpage": ("Hoja de TechDraw activa.", "Active TechDraw sheet.", "Folha do TechDraw ativa."),
    "techobj": ("Hoja activa y un objeto 3D seleccionado.", "Active sheet and a selected 3D object.", "Folha ativa e um objeto 3D selecionado."),
    "techview": ("Hoja activa con una vista.", "Active sheet with a view.", "Folha ativa com uma vista."),
    "techface": ("Cara seleccionada en la vista.", "Face selected in the view.", "Face selecionada na vista."),
    "techdim": ("Cota lineal seleccionada.", "Selected linear dimension.", "Cota linear selecionada."),
    "techlines": ("Líneas seleccionadas en la vista.", "Lines selected in the view.", "Linhas selecionadas na vista."),
}

# Cada sección de referencia: (clave del árbol, título por idioma, introducción por idioma)
SECCIONES = [
    ("explorer", ("Diccionario de Explorador (Explorer)", "Explorer Dictionary", "Dicionário do Explorador (Explorer)"),
     ("Archivos, edición, impresión, ventanas y herramientas generales. Se entra diciendo «explorador».",
      "Files, editing, printing, windows and general tools. Enter by saying «explorer».",
      "Arquivos, edição, impressão, janelas e ferramentas gerais. Entra-se dizendo «explorador».")),
    ("stdview", ("Vistas estándar (StdView)", "Standard Views (StdView)", "Vistas padrão (StdView)"),
     ("Vistas, zoom, cámara, apariencia, paneles y árbol. Se entra diciendo «vista estándar»; las vistas y el zoom también se dicen desde cualquier contexto.",
      "Views, zoom, camera, appearance, panels and tree. Enter by saying «standard view»; views and zoom can also be said from any context.",
      "Vistas, zoom, câmera, aparência, painéis e árvore. Entra-se dizendo «vista padrão»; as vistas e o zoom também se dizem de qualquer contexto.")),
    ("lineattributes", ("Atributos de línea (LineAttributes)", "Line Attributes (LineAttributes)", "Atributos de linha (LineAttributes)"),
     ("Estilo, grosor y color de línea de las vistas de TechDraw.",
      "Line style, width and color for TechDraw views.",
      "Estilo, espessura e cor de linha das vistas do TechDraw.")),
    ("selection", ("Herramienta de Selección (Selection)", "Selection Tool (Selection)", "Ferramenta de Seleção (Selection)"),
     ("Recorre los objetos del documento por voz, sin mouse: el objeto alcanzado se resalta en la vista 3D y en el árbol. Se entra diciendo «selección».",
      "Steps through document objects by voice, without a mouse: the object reached is highlighted in the 3D view and in the tree. Enter by saying «selection».",
      "Percorre os objetos do documento por voz, sem mouse: o objeto alcançado é destacado na vista 3D e na árvore. Entra-se dizendo «seleção».")),
    ("workbench/assembly", ("Banco de trabajo: Ensamblaje (Assembly)", "Workbench: Assembly", "Bancada: Montagem (Assembly)"),
     ("Se entra con «banco de trabajo» → «ensamblaje».", "Enter with «workbench» → «assembly».", "Entra-se com «bancada» → «montagem».")),
    ("workbench/techdraw", ("Banco de trabajo: Planos técnicos (TechDraw)", "Workbench: Technical Drawings (TechDraw)", "Bancada: Desenhos técnicos (TechDraw)"),
     ("Se entra con «banco de trabajo» → «dibujo técnico».", "Enter with «workbench» → «technical drawing».", "Entra-se com «bancada» → «desenho técnico».")),
    ("workbench/partdesign", ("Banco de trabajo: PartDesign", "Workbench: PartDesign", "Bancada: PartDesign"),
     ("Se entra con «banco de trabajo» → «diseño de pieza». Los grupos «base», «agregar», «restar», «editar», «transformaciones» y «administrar» tienen su propio ícono.",
      "Enter with «workbench» → «part design». The groups «base», «additive», «subtractive», «modify», «transform» and «manage» each have their own icon.",
      "Entra-se com «bancada» → «projeto de peça». Os grupos «base», «adicionar», «subtrair», «editar», «transformações» e «gerenciar» têm cada um o seu ícone.")),
    ("workbench/sketcher", ("Banco de trabajo: Croquis (Sketcher)", "Workbench: Sketcher", "Bancada: Croqui (Sketcher)"),
     ("Se entra con «banco de trabajo» → «croquis».", "Enter with «workbench» → «sketcher».", "Entra-se com «bancada» → «croqui».")),
    ("workbench/draft", ("Banco de trabajo: Borrador (Draft)", "Workbench: Draft", "Bancada: Rascunho (Draft)"),
     ("Se entra con «banco de trabajo» → «borrador».", "Enter with «workbench» → «draft».", "Entra-se com «bancada» → «rascunho».")),
    ("workbench/part", ("Banco de trabajo: Pieza (Part)", "Workbench: Part", "Bancada: Peça (Part)"),
     ("Sólidos, primitivas y operaciones CSG. Se entra con «banco de trabajo» → «pieza».", "Solids, primitives and CSG operations. Enter with «workbench» → «part».", "Sólidos, primitivas e operações CSG. Entra-se com «bancada» → «peça».")),
]

T = {
    "es": {
        "lang_name": "Español", "html_lang": "es",
        "title": "DAV — Diseño Asistido por Voz", "subtitle": "Manual de Usuario",
        "lead": ["<b>DAV</b> es un desarrollo inclusivo pensado para promover la participación de personas con discapacidad motriz en el diseño 2D/3D.",
                 "El objetivo del proyecto es permitir que personas con discapacidad motriz puedan crear y modificar modelos, dibujos y piezas 3D mediante comandos de voz. De esta manera, se busca ofrecer una alternativa de interacción por voz que complemente el teclado y el mouse dentro del entorno CAD, ampliando las posibilidades de participación y fomentando la accesibilidad tecnológica."],
        "toc": "Índice", "header": "Manual de Usuario - Proyecto DAV",
        "col_icon": "Ícono", "col_cmd": "Comando (Español)", "col_what": "¿Qué hace?", "col_req": "Requisitos",
        "voice_access": "Acceso por voz", "group_word": "Grupo", "icon_word": "Ícono",
        "part_i": "Uso general", "part_ii": "Bancos de trabajo", "part_ref": "Guía completa de comandos",
        "intro_h": "Introducción",
        "intro": [
            ("Introducción", "<p>El proyecto DAV (Diseño Asistido por Voz) es una herramienta diseñada para facilitar la interacción con sistemas CAD mediante comandos de voz, permitiendo una experiencia de diseño más accesible e integrada.</p>"),
            ("Primeros pasos", "<p>El sistema se fundamenta en FreeCAD 1.1 (probado con la versión 1.1.3). Asegúrese de tenerlo instalado para garantizar la compatibilidad con nuestra capa de control por voz. Las guías de instalación están en <i>Dav/docs/</i>.</p>"),
            ("Interfaz y comandos", "<p><b>Interfaz gráfica:</b> desarrollada con PySide, permite visualizar el árbol de objetos, los botones de cada contexto y configurar preferencias.</p><p><b>Control por voz:</b> utiliza el motor Vosk. El sistema reconoce comandos específicos que se traducen en acciones dentro de FreeCAD.</p><p><b>Modos de visualización:</b> soporte para modos claro y oscuro, integrados con los ajustes nativos del software.</p>"),
            ("Funcionalidades principales", "<ul><li>Dibujo 2D y 3D (bancos de trabajo Draft, Part, PartDesign, Sketcher, Assembly y TechDraw).</li><li>Navegación por voz entre archivos, proyectos e impresión.</li><li>Selección de objetos mediante voz, con respuesta visual en el árbol de objetos.</li><li>Corrección por voz: deshacer, rehacer y borrar objetos con confirmación.</li><li>Ejemplos guiados paso a paso dentro de DAV.</li><li>Soporte multilingüe (español, inglés, portugués).</li></ul>"),
            ("Asistencia y preferencias", "<p>Utilice el panel de preferencias para ajustar el modelo de voz según la memoria RAM disponible en su equipo (modelos pequeños para bajo consumo, grandes para mayor precisión).</p>"),
        ],
        "nav_h": "Funcionamiento general de la navegación por voz",
        "nav_intro": "El sistema DAV opera mediante contextos jerárquicos (navegación por niveles):",
        "nav_steps": [
            "<b>Acceso inicial:</b> desde el nivel Base, decir «explorador» o «archivo» para ingresar al submenú Explorer, «selección» para el control de selección de objetos, «banco de trabajo» para los bancos de trabajo o «vista estándar» para las vistas.",
            "<b>Submenús (entrar):</b> al pronunciar una categoría (por ejemplo «archivo», «editar», «agregar»), el sistema desciende a ese nivel y habilita exclusivamente sus comandos.",
            "<b>Comandos ejecutables:</b> realizan la acción en FreeCAD al ser dictados.",
            "<b>Subir de nivel:</b> en cualquier subcontexto, dictar «subir», «atrás» o «volver» regresa al nivel superior.",
            "<b>Ver estado:</b> dictar «contexto» o «dónde estoy» lista las opciones disponibles en pantalla.",
        ],
        "global_h": "Comandos globales y de navegación",
        "global_intro": "Se pueden decir en cualquier contexto, sin navegar hasta su submenú.",
        "nav_table_h": "Navegación y confirmación",
        "nav_rows": {"up": ("Sube un nivel en el árbol de contextos.", "Ninguno."),
                     "show_context": ("Lista los submenús y comandos disponibles en el nivel actual.", "Ninguno."),
                     "send": ("Confirma el valor o la opción dictada en un diálogo de voz.", "Un diálogo de voz abierto."),
                     "cancel": ("Descarta la frase en curso o cierra el diálogo de voz.", "Ninguno.")},
        "nav_names": {"up": "Subir", "show_context": "Contexto", "send": "Confirmar", "cancel": "Cancelar"},
        "global_table_h": "Corrección, medida, vista y panel",
        "global_names": {"undo": "Deshacer", "redo": "Rehacer", "deleteLast": "Borrar último", "deleteObject": "Borrar objeto",
                         "deleteBroken": "Borrar rotos", "CreateDimension": "Medir / cotar", "MoveView": "Mover vista",
                         "ayuda": "Ayuda"},
        "panel_names": {"preferences": "Preferencias", "hide_dav_panel": "Minimizar panel", "show_dav_panel": "Maximizar panel"},
        "global_views": "Las <b>vistas estándar y el zoom</b> (frontal, arriba, iso, acercar, alejar, ajustar todo…) también se dicen desde cualquier contexto; están en la sección <i>Vistas estándar</i>.",
        "numbers_h": "Cómo se dictan los números",
        "numbers": ["Los números de 0 a 99 se dicen naturales («treinta y dos»). De 100 en adelante se dicen dígito por dígito («dos cinco cero» = 250).",
                    "Los decimales llevan «punto» (en español también «coma»): «uno punto cinco». Los negativos llevan «menos».",
                    "Cada valor se dice y se confirma con «okey» (o «enviar», «aceptar») en una frase aparte."],
        "group_hint": "Grupo — se entra diciendo:", "say": "decí", "also": "también",
        "flat_hint": "Se dice directamente desde este banco de trabajo.",
        "repo_h": "Ubicación de archivos en el repositorio",
        "repo": [("Diccionarios de comandos", "<i>Dav/dic/</i>: cada carpeta tiene su <i>TraduceToEs.py</i> (español), <i>TraduceToEn.py</i> (inglés) y <i>TraduceToPt.py</i> (portugués)."),
                 ("Íconos SVG", "Junto a cada comando, con el nombre de su clave (por ejemplo <i>save.svg</i>); los propios del panel en <i>Dav/scr/ComponentesDAV/InterfazDAV/Icons/</i>."),
                 ("Motor de selección", "<i>Dav/scr/selection/object_selection.py</i>."),
                 ("Navegación global", "<i>Dav/dic/NavCommands/</i> (subir, contexto, enviar, cancelar) y <i>Dav/dic/Correction/</i> (deshacer, borrar)."),
                 ("Guías y manuales", "<i>Dav/docs/</i>. Este manual se genera con <i>Dav/docs/manual/build_manual.py</i> a partir de los diccionarios reales.")],
        "ex_h": "Ejemplos guiados", "ex_sub": "Aprender haciendo",
        "ex_intro": "DAV trae ejemplos que se arman paso a paso, por voz. Cada cuadro te dice qué decir; cuando lo decís todo, en orden, la acción se ejecuta y pasa al cuadro siguiente.",
        "ex_open_h": "Cómo abrir un ejemplo",
        "ex_open": ["Decí <b>explorador</b>, después <b>ejemplos</b> y otra vez <b>ejemplos</b>: se abre el selector.",
                    "Con <b>avanzar</b> (o <b>retroceder</b>) recorré la lista hasta el ejemplo y decí <b>enviar</b>.",
                    "Una ventana, que no bloquea FreeCAD, muestra un cuadro por vez con lo que dirías para hacerlo: primero el camino por los menús y después los valores. Cada valor se confirma con <b>enviar</b>.",
                    "<b>saltar</b> ejecuta el cuadro sin decir sus palabras; <b>cancelar</b> cierra el ejemplo; al terminar, <b>enviar</b> lo cierra.",
                    "Los números de 0 a 99 se dicen naturales («treinta y dos»); de 100 en adelante, dígito por dígito. Los decimales llevan «punto» o «coma»."],
        "ex_list_h": "Ejemplos disponibles", "ex_col_ex": "Ejemplo", "ex_col_what": "Qué se hace",
        "ex_desc": {
            "sketcher": "Un círculo con restricción de radio y cota en 2D.",
            "draft": "Rectángulo, círculo y polígono con medidas dictadas.",
            "casa": "Una casa con figuras 2D de medidas dictadas; se aprende a recortar una figura con otra.",
            "rotulo": "Un rótulo simple con texto en Draft.",
            "techdraw": "Un círculo en una hoja de TechDraw con su rótulo.",
            "partdesign": "Un tornillo: vástago, punta, cabeza, chaflán y rosca; cota en 3D y vista «tres de».",
            "dado": "Un dado de 20 mm: la cara del 1 con un cilindro y las otras cinco con un boceto y un vaciado cada una.",
            "arandela": "Una arandela M6: croquis con el agujero (Ø 6,4) y el borde (Ø 12), extruido 1,6 mm y puesto en una hoja de TechDraw.",
            "bulontuerca": "Un bulón M6 y su tuerca en PartDesign, unidos en un ensamblaje con junta cilíndrica.",
            "tijeras": "Dos hojas, dos mangos y un perno unidos en un ensamblaje con bisagras y juntas fijas.",
        },
        "ex_casa_h": "Casa: figuras 2D (Draft)",
        "ex_casa_p": "Se dibuja una casa solo con figuras 2D de medidas dictadas, y se aprende a recortar una figura con otra.",
        "ex_casa": [("Cuerpo", "rectángulo por esquinas, de (2, 0) a (42, 25)"),
                    ("Techo", "triángulo por vértices (0, 25), (44, 25) y (22, 50)"),
                    ("Puerta y ventanas", "rectángulo por esquinas de (17, 0) a (27, 14); dos «rectángulo por centro» de 8 × 8 en (10, 14) y (34, 14)"),
                    ("Chimenea", "rectángulo de (31, 30) a (37, 48) y un triángulo como gorro; se recorta con modificar → cortar"),
                    ("Detalles", "ventana redonda (círculo en (22, 34), radio 5), picaporte (radio 1) y la cruz de las ventanas con líneas por puntos")],
        "ex_casa_path": "Camino: banco → borrador → crear → rectángulo / triángulo / círculo, y subir → dibujo → línea para las líneas.",
        "ex_casa_cap": "Resultado del ejemplo de la casa",
        "ex_bulon_h": "Bulón-tuerca: un ensamblaje (PartDesign y Assembly)",
        "ex_bulon_p": "Un bulón M6 (simplificado de la DIN 931) y su tuerca, hechos en PartDesign y unidos en un ensamblaje.",
        "ex_bulon": [("Vástago", "cilindro de radio 3 y 20 de alto, centro en (0, 0, 10)"),
                     ("Cabeza", "prisma de 6 lados, radio 6 y 4 de alto, centro en (0, 0, 22), sumado al mismo cuerpo"),
                     ("Tuerca", "otro cuerpo: prisma de 6 lados, radio 6 y 5 de alto, en (15, 0, 4), con un cilindro sustractivo de radio 3"),
                     ("Ensamblaje", "crear ensamblaje, dos veces insertar vínculo, anclar pieza (el bulón) y una junta de cilindro por los cilindros del vástago y del agujero; resolver y la vista «tres de»")],
        "ex_bulon_cap": "Bulón y tuerca, vista isométrica",
        "ex_tij_h": "Tijera de 5 piezas: ensamblaje y plano (PartDesign y Assembly)",
        "ex_tij_p": "Dos hojas, dos mangos y un perno: cinco piezas en PartDesign, unidas en un ensamblaje con bisagras y juntas fijas.",
        "ex_tij": [("Hojas", "triángulo por vértices (80, 0), (-10, -16), (-26, 14) extruido 2 mm, más una lengüeta y dos agujeros; la hoja B es su espejo en Y"),
                   ("Mangos", "anillos de radio 14 y 4 de alto, con un hueco de radio 8, en (-32, ±18)"),
                   ("Perno", "escalonado (radio 2 y 1,8): así el ensamblaje apila la hoja B 2 mm sobre la A sin juntas de posición"),
                   ("Ensamblaje", "5 × insertar vínculo, anclar pieza (el perno), dos bisagra (hojas) y dos ensamble fijo (hoja-mango); resolver y «tres de»")],
        "ex_tij_note": "El ejemplo de DAV llega hasta la tijera cerrada. La guía <i>Dav/docs/guia-tijeras-voz.md</i> sigue con la tijera abierta al 50 % (una junta por distancia de 23,3 mm entre los mangos) y con el plano técnico en hoja ANSI B (ASME Y14.1, proyección en tercer ángulo).",
        "ex_tij_cap": "Plano de la tijera: vista lateral abierta al 50 % y vista isométrica cerrada",
        "ack_h": "Agradecimientos",
        "ack": ["Queremos agradecer especialmente a la Universidad Autónoma de Entre Ríos (UADER) por brindarnos el espacio y los recursos necesarios para llevar adelante este proyecto; a los profesores Jesús Valenzuela y Bernabe Arias, por su acompañamiento, orientación y disposición durante el proceso; y a los comunicadores Naitria Peralta Montoya y Bruno Contigiani, por su colaboración y aportes en el desarrollo y difusión del proyecto.",
                "A todas las personas que, de una u otra manera, contribuyeron a que este proyecto fuera posible, muchas gracias."],
        "page": "pág.",
    },
    "en": {
        "lang_name": "English", "html_lang": "en",
        "title": "DAV — Voice-Assisted Design", "subtitle": "User Manual",
        "lead": ["<b>DAV</b> is an inclusive development designed to promote the participation of people with motor disabilities in 2D/3D design.",
                 "The goal of the project is to enable people with motor disabilities to create and modify 3D models, drawings, and parts through spoken instructions. In doing so, it seeks to offer a voice-based alternative that complements the keyboard and mouse within the CAD environment, broadening opportunities for participation and promoting technological accessibility."],
        "toc": "Contents", "header": "User Manual - DAV Project",
        "col_icon": "Icon", "col_cmd": "Voice commands (English)", "col_what": "What does it do?", "col_req": "Requirements",
        "voice_access": "Voice access", "group_word": "Group", "icon_word": "Icon",
        "part_i": "General use", "part_ii": "Workbenches", "part_ref": "Complete command guide",
        "intro_h": "Introduction",
        "intro": [
            ("Introduction", "<p>The DAV (Voice-Assisted Design) project is a tool designed to facilitate interaction with CAD systems through voice commands, providing a more accessible and integrated design experience.</p>"),
            ("Getting started", "<p>The system is based on FreeCAD 1.1 (tested with version 1.1.3). Make sure it is installed to ensure compatibility with our voice control layer. Installation guides are in <i>Dav/docs/</i>.</p>"),
            ("Interface and commands", "<p><b>Graphical interface:</b> developed with PySide, it shows the object tree, the buttons of each context and lets you configure preferences.</p><p><b>Voice control:</b> uses the Vosk engine. The system recognizes specific commands that are translated into actions within FreeCAD.</p><p><b>Display modes:</b> supports light and dark modes, integrated with the software's native settings.</p>"),
            ("Main features", "<ul><li>2D and 3D drawing (Draft, Part, PartDesign, Sketcher, Assembly and TechDraw workbenches).</li><li>Voice navigation between files, projects and printing.</li><li>Voice-based object selection with visual feedback in the object tree.</li><li>Voice corrections: undo, redo and delete objects with confirmation.</li><li>Step-by-step guided examples inside DAV.</li><li>Multilingual support (Spanish, English, Portuguese).</li></ul>"),
            ("Assistance and preferences", "<p>Use the preferences panel to adjust the speech model based on your system's available RAM (small models for low consumption, large for higher accuracy).</p>"),
        ],
        "nav_h": "General operation of voice navigation",
        "nav_intro": "The DAV system operates through hierarchical contexts (level navigation):",
        "nav_steps": [
            "<b>Initial access:</b> from the Base level, say «explorer» or «file» to enter the Explorer submenu, «selection» for object selection, «workbench» for the workbenches or «standard view» for the views.",
            "<b>Submenus (enter):</b> when you say a category (e.g. «file», «edit», «additive»), the system descends to that level and enables only its commands.",
            "<b>Executable commands:</b> perform the action in FreeCAD when spoken.",
            "<b>Go up a level:</b> in any subcontext, saying «up», «back» or «go back» returns to the upper level.",
            "<b>View status:</b> saying «context» or «where am I» lists the available options on screen.",
        ],
        "global_h": "Global and navigation commands",
        "global_intro": "They can be said in any context, without navigating to their submenu.",
        "nav_table_h": "Navigation and confirmation",
        "nav_rows": {"up": ("Goes up one level in the context tree.", "None."),
                     "show_context": ("Lists the submenus and commands available at the current level.", "None."),
                     "send": ("Confirms the value or option dictated in a voice dialog.", "An open voice dialog."),
                     "cancel": ("Discards the phrase in progress or closes the voice dialog.", "None.")},
        "nav_names": {"up": "Up", "show_context": "Context", "send": "Confirm", "cancel": "Cancel"},
        "global_table_h": "Correction, measure, view and panel",
        "global_names": {"undo": "Undo", "redo": "Redo", "deleteLast": "Delete last", "deleteObject": "Delete object",
                         "deleteBroken": "Delete broken", "CreateDimension": "Measure / dimension", "MoveView": "Move view",
                         "ayuda": "Help"},
        "panel_names": {"preferences": "Preferences", "hide_dav_panel": "Minimize panel", "show_dav_panel": "Maximize panel"},
        "global_views": "The <b>standard views and zoom</b> (front, top, iso, zoom in, zoom out, fit all…) can also be said from any context; they are in the <i>Standard Views</i> section.",
        "numbers_h": "How numbers are dictated",
        "numbers": ["Numbers from 0 to 99 are said naturally («thirty two»). From 100 on they are said digit by digit («two five zero» = 250).",
                    "Decimals use «point»: «one point five». Negatives use «minus».",
                    "Each value is said and confirmed with «okay» (or «send», «accept») in a separate phrase."],
        "group_hint": "Group — enter by saying:", "say": "say", "also": "also",
        "flat_hint": "Said directly from this workbench.",
        "repo_h": "File locations in the repository",
        "repo": [("Command dictionaries", "<i>Dav/dic/</i>: each folder has its <i>TraduceToEs.py</i> (Spanish), <i>TraduceToEn.py</i> (English) and <i>TraduceToPt.py</i> (Portuguese)."),
                 ("SVG icons", "Next to each command, named after its key (for example <i>save.svg</i>); the panel's own icons are in <i>Dav/scr/ComponentesDAV/InterfazDAV/Icons/</i>."),
                 ("Selection engine", "<i>Dav/scr/selection/object_selection.py</i>."),
                 ("Global navigation", "<i>Dav/dic/NavCommands/</i> (up, context, send, cancel) and <i>Dav/dic/Correction/</i> (undo, delete)."),
                 ("Guides and manuals", "<i>Dav/docs/</i>. This manual is generated with <i>Dav/docs/manual/build_manual.py</i> from the real dictionaries.")],
        "ex_h": "Guided examples", "ex_sub": "Learning by doing",
        "ex_intro": "DAV ships with examples that are built step by step, by voice. Each frame tells you what to say; when you have said it all, in order, the action runs and the next frame appears.",
        "ex_open_h": "How to open an example",
        "ex_open": ["Say <b>explorer</b>, then <b>examples</b> and <b>examples</b> again: the picker opens.",
                    "With <b>next</b> (or <b>back</b>) go through the list to the example and say <b>send</b>.",
                    "A window, which does not block FreeCAD, shows one frame at a time with what you would say to do it: first the path through the menus and then the values. Each value is confirmed with <b>send</b>.",
                    "<b>skip</b> runs the frame without saying its words; <b>cancel</b> closes the example; at the end, <b>send</b> closes it.",
                    "Numbers from 0 to 99 are said naturally («thirty two»); from 100 on, digit by digit. Decimals use «point»."],
        "ex_list_h": "Available examples", "ex_col_ex": "Example", "ex_col_what": "What is done",
        "ex_desc": {
            "sketcher": "A circle with a radius constraint and a 2D dimension.",
            "draft": "Rectangle, circle and polygon with dictated sizes.",
            "casa": "A house from 2D shapes with dictated sizes; you learn to trim one shape with another.",
            "rotulo": "A simple title block with text in Draft.",
            "techdraw": "A circle on a TechDraw sheet with its title block.",
            "partdesign": "A screw: shank, tip, head, chamfer and thread; 3D dimension and «isometric» view.",
            "dado": "A 20 mm die: the 1 face with a cylinder and the other five with a sketch and a pocket each.",
            "arandela": "An M6 washer: sketch with the hole (Ø 6.4) and the edge (Ø 12), extruded 1.6 mm and placed on a TechDraw sheet.",
            "bulontuerca": "An M6 bolt and its nut in PartDesign, joined in an assembly with a cylindrical joint.",
            "tijeras": "Two blades, two handles and a bolt joined in an assembly with hinges and fixed joints.",
        },
        "ex_casa_h": "House: 2D shapes (Draft)",
        "ex_casa_p": "A house is drawn with 2D shapes only, with dictated sizes, and you learn to trim one shape with another.",
        "ex_casa": [("Body", "rectangle by corners, from (2, 0) to (42, 25)"),
                    ("Roof", "triangle by vertices (0, 25), (44, 25) and (22, 50)"),
                    ("Door and windows", "rectangle by corners from (17, 0) to (27, 14); two «rectangle by center» of 8 × 8 at (10, 14) and (34, 14)"),
                    ("Chimney", "rectangle from (31, 30) to (37, 48) and a triangle as its cap; trimmed with modify → cut"),
                    ("Details", "round window (circle at (22, 34), radius 5), door knob (radius 1) and the window crosses with lines by points")],
        "ex_casa_path": "Path: workbench → draft → create → rectangle / triangle / circle, and up → drawing → line for the lines.",
        "ex_casa_cap": "Result of the house example",
        "ex_bulon_h": "Bolt and nut: an assembly (PartDesign and Assembly)",
        "ex_bulon_p": "An M6 bolt (simplified from DIN 931) and its nut, made in PartDesign and joined in an assembly.",
        "ex_bulon": [("Shank", "cylinder with radius 3 and height 20, centered at (0, 0, 10)"),
                     ("Head", "6-sided prism, radius 6 and height 4, centered at (0, 0, 22), added to the same body"),
                     ("Nut", "another body: 6-sided prism, radius 6 and height 5, at (15, 0, 4), with a subtractive cylinder of radius 3"),
                     ("Assembly", "create assembly, insert link twice, ground part (the bolt) and a cylindrical joint through the shank and hole cylinders; solve and the «isometric» view")],
        "ex_bulon_cap": "Bolt and nut, isometric view",
        "ex_tij_h": "Five-part scissors: assembly and drawing (PartDesign and Assembly)",
        "ex_tij_p": "Two blades, two handles and a bolt: five parts in PartDesign, joined in an assembly with hinges and fixed joints.",
        "ex_tij": [("Blades", "triangle by vertices (80, 0), (-10, -16), (-26, 14) extruded 2 mm, plus a tab and two holes; blade B is its mirror in Y"),
                   ("Handles", "rings of radius 14 and height 4, with a hole of radius 8, at (-32, ±18)"),
                   ("Bolt", "stepped (radius 2 and 1.8): this way the assembly stacks blade B 2 mm above A without position joints"),
                   ("Assembly", "5 × insert link, ground part (the bolt), two hinge (blades) and two fixed joint (blade-handle); solve and «isometric»")],
        "ex_tij_note": "The DAV example goes as far as the closed scissors. The guide <i>Dav/docs/guia-tijeras-voz.md</i> continues with the scissors open at 50 % (a distance joint of 23.3 mm between the handles) and the technical drawing on an ANSI B sheet (ASME Y14.1, third-angle projection).",
        "ex_tij_cap": "Scissors drawing: side view open at 50 % and closed isometric view",
        "ack_h": "Acknowledgements",
        "ack": ["We would like to extend our special thanks to the Autonomous University of Entre Ríos (UADER) for providing us with the space and resources necessary to carry out this project; to professors Jesús Valenzuela and Bernabe Arias, for their support, guidance, and willingness throughout the process; and to communicators Naitria Peralta Montoya and Bruno Contigiani, for their collaboration and contributions to the development and dissemination of the project.",
                "To everyone who, in one way or another, contributed to making this project possible, thank you very much."],
        "page": "p.",
    },
    "pt": {
        "lang_name": "Português", "html_lang": "pt",
        "title": "DAV — Desenho Assistido por Voz", "subtitle": "Manual do Usuário",
        "lead": ["<b>DAV</b> é um desenvolvimento inclusivo pensado para promover a participação de pessoas com deficiência motora no desenho 2D/3D.",
                 "O objetivo do projeto é permitir que pessoas com deficiência motora possam criar e modificar modelos, desenhos e peças 3D por meio de comandos de voz. Dessa forma, busca-se oferecer uma alternativa de interação por voz que complemente o teclado e o mouse no ambiente CAD, ampliando as possibilidades de participação e fomentando a acessibilidade tecnológica."],
        "toc": "Índice", "header": "Manual do Usuário - Projeto DAV",
        "col_icon": "Ícone", "col_cmd": "Comando (Português)", "col_what": "O que faz?", "col_req": "Requisitos",
        "voice_access": "Acesso por voz", "group_word": "Grupo", "icon_word": "Ícone",
        "part_i": "Uso geral", "part_ii": "Bancadas de trabalho", "part_ref": "Guia completo de comandos",
        "intro_h": "Introdução",
        "intro": [
            ("Introdução", "<p>O projeto DAV (Desenho Assistido por Voz) é uma ferramenta projetada para facilitar a interação com sistemas CAD por meio de comandos de voz, permitindo uma experiência de projeto mais acessível e integrada.</p>"),
            ("Primeiros passos", "<p>O sistema é baseado no FreeCAD 1.1 (testado com a versão 1.1.3). Certifique-se de tê-lo instalado para garantir a compatibilidade com nossa camada de controle por voz. Os guias de instalação estão em <i>Dav/docs/</i>.</p>"),
            ("Interface e comandos", "<p><b>Interface gráfica:</b> desenvolvida com PySide, permite visualizar a árvore de objetos, os botões de cada contexto e configurar preferências.</p><p><b>Controle por voz:</b> utiliza o motor Vosk. O sistema reconhece comandos específicos que são traduzidos em ações dentro do FreeCAD.</p><p><b>Modos de visualização:</b> suporte aos modos claro e escuro, integrados às configurações nativas do software.</p>"),
            ("Funcionalidades principais", "<ul><li>Desenho 2D e 3D (bancadas Draft, Part, PartDesign, Sketcher, Assembly e TechDraw).</li><li>Navegação por voz entre arquivos, projetos e impressão.</li><li>Seleção de objetos por voz, com resposta visual na árvore de objetos.</li><li>Correção por voz: desfazer, refazer e apagar objetos com confirmação.</li><li>Exemplos guiados passo a passo dentro do DAV.</li><li>Suporte multilíngue (espanhol, inglês, português).</li></ul>"),
            ("Assistência e preferências", "<p>Use o painel de preferências para ajustar o modelo de voz conforme a memória RAM disponível no seu equipamento (modelos pequenos para baixo consumo, grandes para maior precisão).</p>"),
        ],
        "nav_h": "Funcionamento geral da navegação por voz",
        "nav_intro": "O sistema DAV opera por meio de contextos hierárquicos (navegação por níveis):",
        "nav_steps": [
            "<b>Acesso inicial:</b> a partir do nível Base, diga «explorador» ou «arquivo» para entrar no submenu Explorer, «seleção» para o controle de seleção de objetos, «bancada de trabalho» para as bancadas ou «vista padrão» para as vistas.",
            "<b>Submenus (entrar):</b> ao pronunciar uma categoria (ex.: «arquivo», «editar», «adicionar»), o sistema desce a esse nível e habilita exclusivamente seus comandos.",
            "<b>Comandos executáveis:</b> realizam a ação no FreeCAD assim que são ditados.",
            "<b>Subir de nível:</b> em qualquer subcontexto, dizer «subir», «voltar» ou «atrás» retorna ao nível superior.",
            "<b>Ver estado:</b> dizer «contexto» ou «onde estou» lista as opções disponíveis na tela.",
        ],
        "global_h": "Comandos globais e de navegação",
        "global_intro": "Podem ser ditos em qualquer contexto, sem navegar até o seu submenu.",
        "nav_table_h": "Navegação e confirmação",
        "nav_rows": {"up": ("Sobe um nível na árvore de contextos.", "Nenhum."),
                     "show_context": ("Lista os submenus e comandos disponíveis no nível atual.", "Nenhum."),
                     "send": ("Confirma o valor ou a opção ditada em um diálogo de voz.", "Um diálogo de voz aberto."),
                     "cancel": ("Descarta a frase em andamento ou fecha o diálogo de voz.", "Nenhum.")},
        "nav_names": {"up": "Subir", "show_context": "Contexto", "send": "Confirmar", "cancel": "Cancelar"},
        "global_table_h": "Correção, medida, vista e painel",
        "global_names": {"undo": "Desfazer", "redo": "Refazer", "deleteLast": "Apagar último", "deleteObject": "Apagar objeto",
                         "deleteBroken": "Apagar quebrados", "CreateDimension": "Medir / cotar", "MoveView": "Mover vista",
                         "ayuda": "Ajuda"},
        "panel_names": {"preferences": "Preferências", "hide_dav_panel": "Minimizar painel", "show_dav_panel": "Maximizar painel"},
        "global_views": "As <b>vistas padrão e o zoom</b> (frontal, topo, iso, aproximar, afastar, ajustar tudo…) também se dizem de qualquer contexto; estão na seção <i>Vistas padrão</i>.",
        "numbers_h": "Como se ditam os números",
        "numbers": ["Os números de 0 a 99 se dizem naturalmente («trinta e dois»). De 100 em diante se dizem dígito por dígito («dois cinco zero» = 250).",
                    "Os decimais levam «ponto»: «um ponto cinco». Os negativos levam «menos».",
                    "Cada valor é dito e confirmado com «okey» (ou «enviar», «aceitar») em uma frase separada."],
        "group_hint": "Grupo — entra-se dizendo:", "say": "diga", "also": "também",
        "flat_hint": "Dito diretamente a partir desta bancada.",
        "repo_h": "Localização dos arquivos no repositório",
        "repo": [("Dicionários de comandos", "<i>Dav/dic/</i>: cada pasta tem seu <i>TraduceToEs.py</i> (espanhol), <i>TraduceToEn.py</i> (inglês) e <i>TraduceToPt.py</i> (português)."),
                 ("Ícones SVG", "Ao lado de cada comando, com o nome da sua chave (por exemplo <i>save.svg</i>); os próprios do painel em <i>Dav/scr/ComponentesDAV/InterfazDAV/Icons/</i>."),
                 ("Motor de seleção", "<i>Dav/scr/selection/object_selection.py</i>."),
                 ("Navegação global", "<i>Dav/dic/NavCommands/</i> (subir, contexto, enviar, cancelar) e <i>Dav/dic/Correction/</i> (desfazer, apagar)."),
                 ("Guias e manuais", "<i>Dav/docs/</i>. Este manual é gerado com <i>Dav/docs/manual/build_manual.py</i> a partir dos dicionários reais.")],
        "ex_h": "Exemplos guiados", "ex_sub": "Aprender fazendo",
        "ex_intro": "O DAV traz exemplos que se montam passo a passo, por voz. Cada quadro diz o que falar; quando você diz tudo, em ordem, a ação é executada e passa ao quadro seguinte.",
        "ex_open_h": "Como abrir um exemplo",
        "ex_open": ["Diga <b>explorador</b>, depois <b>exemplos</b> e outra vez <b>exemplos</b>: o seletor é aberto.",
                    "Com <b>avançar</b> (ou <b>retroceder</b>) percorra a lista até o exemplo e diga <b>enviar</b>.",
                    "Uma janela, que não bloqueia o FreeCAD, mostra um quadro por vez com o que você diria para fazê-lo: primeiro o caminho pelos menus e depois os valores. Cada valor é confirmado com <b>enviar</b>.",
                    "<b>pular</b> executa o quadro sem dizer suas palavras; <b>cancelar</b> fecha o exemplo; ao terminar, <b>enviar</b> o fecha.",
                    "Os números de 0 a 99 se dizem naturalmente («trinta e dois»); de 100 em diante, dígito por dígito. Os decimais levam «ponto»."],
        "ex_list_h": "Exemplos disponíveis", "ex_col_ex": "Exemplo", "ex_col_what": "O que se faz",
        "ex_desc": {
            "sketcher": "Um círculo com restrição de raio e cota em 2D.",
            "draft": "Retângulo, círculo e polígono com medidas ditadas.",
            "casa": "Uma casa com figuras 2D de medidas ditadas; aprende-se a recortar uma figura com outra.",
            "rotulo": "Um carimbo simples com texto no Draft.",
            "techdraw": "Um círculo em uma folha do TechDraw com seu carimbo.",
            "partdesign": "Um parafuso: haste, ponta, cabeça, chanfro e rosca; cota em 3D e vista «três de».",
            "dado": "Um dado de 20 mm: a face do 1 com um cilindro e as outras cinco com um esboço e um rebaixo cada uma.",
            "arandela": "Uma arruela M6: croqui com o furo (Ø 6,4) e a borda (Ø 12), extrudado 1,6 mm e colocado em uma folha do TechDraw.",
            "bulontuerca": "Um parafuso M6 e sua porca no PartDesign, unidos em uma montagem com junta cilíndrica.",
            "tijeras": "Duas lâminas, dois cabos e um pino unidos em uma montagem com dobradiças e juntas fixas.",
        },
        "ex_casa_h": "Casa: figuras 2D (Draft)",
        "ex_casa_p": "Desenha-se uma casa apenas com figuras 2D de medidas ditadas, e aprende-se a recortar uma figura com outra.",
        "ex_casa": [("Corpo", "retângulo por cantos, de (2, 0) a (42, 25)"),
                    ("Telhado", "triângulo por vértices (0, 25), (44, 25) e (22, 50)"),
                    ("Porta e janelas", "retângulo por cantos de (17, 0) a (27, 14); dois «retângulo por centro» de 8 × 8 em (10, 14) e (34, 14)"),
                    ("Chaminé", "retângulo de (31, 30) a (37, 48) e um triângulo como chapéu; recorta-se com modificar → cortar"),
                    ("Detalhes", "janela redonda (círculo em (22, 34), raio 5), maçaneta (raio 1) e a cruz das janelas com linhas por pontos")],
        "ex_casa_path": "Caminho: bancada → rascunho → criar → retângulo / triângulo / círculo, e subir → desenho → linha para as linhas.",
        "ex_casa_cap": "Resultado do exemplo da casa",
        "ex_bulon_h": "Parafuso-porca: uma montagem (PartDesign e Assembly)",
        "ex_bulon_p": "Um parafuso M6 (simplificado da DIN 931) e sua porca, feitos no PartDesign e unidos em uma montagem.",
        "ex_bulon": [("Haste", "cilindro de raio 3 e 20 de altura, centro em (0, 0, 10)"),
                     ("Cabeça", "prisma de 6 lados, raio 6 e 4 de altura, centro em (0, 0, 22), somado ao mesmo corpo"),
                     ("Porca", "outro corpo: prisma de 6 lados, raio 6 e 5 de altura, em (15, 0, 4), com um cilindro subtrativo de raio 3"),
                     ("Montagem", "criar montagem, duas vezes inserir vínculo, ancorar peça (o parafuso) e uma junta de cilindro pelos cilindros da haste e do furo; resolver e a vista «três de»")],
        "ex_bulon_cap": "Parafuso e porca, vista isométrica",
        "ex_tij_h": "Tesoura de 5 peças: montagem e desenho (PartDesign e Assembly)",
        "ex_tij_p": "Duas lâminas, dois cabos e um pino: cinco peças no PartDesign, unidas em uma montagem com dobradiças e juntas fixas.",
        "ex_tij": [("Lâminas", "triângulo por vértices (80, 0), (-10, -16), (-26, 14) extrudado 2 mm, mais uma lingueta e dois furos; a lâmina B é o seu espelho em Y"),
                   ("Cabos", "anéis de raio 14 e 4 de altura, com um vazio de raio 8, em (-32, ±18)"),
                   ("Pino", "escalonado (raio 2 e 1,8): assim a montagem empilha a lâmina B 2 mm sobre a A sem juntas de posição"),
                   ("Montagem", "5 × inserir vínculo, ancorar peça (o pino), duas dobradiça (lâminas) e duas junta fixa (lâmina-cabo); resolver e «três de»")],
        "ex_tij_note": "O exemplo do DAV vai até a tesoura fechada. O guia <i>Dav/docs/guia-tijeras-voz.md</i> segue com a tesoura aberta a 50 % (uma junta de distância de 23,3 mm entre os cabos) e com o desenho técnico em folha ANSI B (ASME Y14.1, projeção no terceiro diedro).",
        "ex_tij_cap": "Desenho da tesoura: vista lateral aberta a 50 % e vista isométrica fechada",
        "ack_h": "Agradecimentos",
        "ack": ["Queremos agradecer especialmente à Universidade Autônoma de Entre Ríos (UADER) por nos oferecer o espaço e os recursos necessários para levar adiante este projeto; aos professores Jesús Valenzuela e Bernabe Arias, pelo acompanhamento, orientação e disposição durante o processo; e aos comunicadores Naitria Peralta Montoya e Bruno Contigiani, pela colaboração e contribuições no desenvolvimento e divulgação do projeto.",
                "A todas as pessoas que, de uma forma ou de outra, contribuíram para que este projeto fosse possível, muito obrigado."],
        "page": "pág.",
    },
}
