def ayuda():
    print("EXPLORADOR DAV - Menú Principal")
    print("Bienvenido al sistema de Diseño Asistido por Voz.")
    print("Actualmente tienes acceso a los siguientes bancos de trabajo:")
    print("")
    print("- Draft: Herramientas de dibujo 2D, anotaciones y modificaciones.")
    print("- TechDraw: Herramientas para la creación de planos técnicos y vistas.")
    print("")
    print("Instrucciones de navegación:")
    print("1. Di el nombre del banco de trabajo (ej: 'draft').")
    print("2. Una vez dentro, di 'help' para conocer sus categorías.")
    print("3. Para ejecutar un comando final, di su nombre en inglés (ej: 'scale').")
    print("========================================")