def ayuda():
    print('Comandos disponibles en este nivel:')
    print('  create - Crea un círculo por centro y radio (ventana por voz, como línea por puntos).')
    print('           Requiere: Centro X (float), Centro Y (float) y Radio (float >0).')
    print('           Alias: create_by_center. Abre un InputPrompt por cada float.')
    print('')
    print('  3point - Crea un círculo que pasa por 3 puntos (ventana por voz, como línea por puntos).')
    print('           Requiere: X1,Y1, X2,Y2, X3,Y3 (float). Los 3 puntos no pueden ser colineales.')
    print('           Alias: create_by_3_points. Abre un InputPrompt por cada coordenada.')
    print('')
    print('  interactive / interactive_3point - Modo mouse legacy (Sketcher_CreateCircle / 3PointCircle).')