def ayuda():
    print('Comandos y subconjuntos disponibles en el nivel raíz de Sketcher:')
    print('  line      - Subconjunto para la creación de líneas rectas en croquis.')
    print('  point     - Subconjunto para la creación de puntos en croquis.')
    print('  polyline  - Subconjunto para la creación de líneas compuestas (polilíneas).')
    print('  rectangle - Subconjunto para la creación de rectángulos (esquinas opuestas, centrado).')
    print('  square    - Subconjunto para la creación de cuadrados regulares.')
    print('  triangle  - Subconjunto para la creación de triángulos equiláteros.')
    print('  hexagon   - Subconjunto para la creación de hexágonos regulares.')
    print('  heptagon  - Subconjunto para la creación de heptágonos regulares.')
    print('  circle    - Subconjunto para la creación de círculos (centro y radio, 3 puntos).')
    print('  arc       - Subconjunto para la creación de arcos circulares (centro, 3 puntos).')
    print('  slot      - Subconjunto para la creación de ojales (ranuras) paramétricos.')
    print('  arc_slot  - Subconjunto para la creación de ranuras curvas (bordes redondeados o planos).')
    print('  oblong    - Subconjunto para la creación de oblongos (ranuras/cápsulas) por centros y radio.')
    print('  text      - Subconjunto para la creación de texto 2D paramétrico (vía ShapeString).')
    print('              (Ejecutar ayuda de cada subconjunto para ver sus comandos en detalle)')